const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token=sessionStorage.getItem('city-token')||'',city=null,page=location.pathname==='/pairing'?'Pairing':'Home',selected=null,ws,generation=0,timer,refreshing=false,pending=false,connection='OFFLINE',selectedNode=null,pairing=null,pairingBusy=false,pairingEpoch=0,pairingNotice='';
const finished=t=>['COMPLETED','FAILED','CANCELLED'].includes(t.state);
async function api(path,body){const r=await fetch('/api/v0/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-City-Api-Version':'0','X-City-Schema-Version':'0'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(5000)});const x=await r.json();if(!r.ok)throw Error(x.error);if(x.apiVersion!==0||x.schemaVersion!==0)throw Error('Protocol mismatch: this client requires version 0');return x;}
function clearPairing(message=''){pairing=null;pairingEpoch++;pairingNotice=message;}
function status(s){if(s!=='ONLINE')clearPairing('Reconnect to generate a pairing session.');connection=s;$('#connection').textContent=s;$('#connection').className=s==='ONLINE'?'online':'';$('#run').disabled=s!=='ONLINE';render();}
async function refresh(){if(refreshing){pending=true;return;}refreshing=true;try{const gen=generation;const snapshot=await api('city');if(gen!==generation)return;city=snapshot;if(pairing&&city.descriptor?.pairingSessionId!==pairing.pairingSessionId)clearPairing('Session used, expired, or replaced. Generate a new session.');$('#pair').hidden=true;$('#content').hidden=false;$('#error').textContent='';render();}finally{refreshing=false;if(pending){pending=false;refresh().catch(disconnected);}}}
function disconnected(e){status('OFFLINE');if(e?.message)$('#error').textContent=e.message;}
async function connect(){const gen=++generation;clearTimeout(timer);ws?.close();status('RECONNECTING');try{await refresh();if(gen!==generation)return;ws=new WebSocket(location.origin.replace(/^http/,'ws')+'/api/v0/events/stream?apiVersion=0&schemaVersion=0',['city-v0','city-token.'+btoa(token).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')]);ws.onopen=()=>{if(gen===generation)status('ONLINE');};ws.onmessage=()=>refresh().catch(disconnected);ws.onerror=()=>disconnected();ws.onclose=()=>{if(gen===generation){disconnected();timer=setTimeout(connect,1800);}};}catch(e){if(gen===generation){disconnected(e);timer=setTimeout(connect,2500);}}}
const badge=s=>`<span class="badge ${esc(s)}">${esc(s)}</span>`;
const taskRows=(tasks,emptyMessage='No tasks yet. Run your first test task.')=>tasks.length?tasks.slice().reverse().map(t=>`<div class="row"><button class="task-open" data-task="${esc(t.id)}">${esc(t.type)}<div class="task-id">${esc(t.id)}</div></button>${badge(t.state)}</div>`).join(''):`<p class="muted">${esc(emptyMessage)}</p>`;
const age=value=>{const ms=Date.now()-Date.parse(value);return Number.isFinite(ms)?Math.max(0,Math.floor(ms/1000))+'s ago':'Unknown';};
const bytes=value=>Number.isFinite(value)?(value/1024**3).toFixed(1)+' GB':'Unknown';
const nodeState=n=>connection!=='ONLINE'?'UNKNOWN':!n.online?'OFFLINE':fresh(n)?'ONLINE':'UNKNOWN';
const fresh=n=>connection==='ONLINE'&&n.online&&Number.isFinite(Date.parse(n.telemetry?.observedAt))&&Date.now()-Date.parse(n.telemetry.observedAt)<=10000&&Date.now()>=Date.parse(n.telemetry.observedAt);
const metrics=n=>{const t=n.telemetry||{},valid=fresh(n);return `<div class="telemetry ${valid?'fresh':'cached'}"><p class="muted">${valid?'Live telemetry':'Cached / UNKNOWN telemetry'} · observed ${esc(age(t.observedAt))}</p><dl class="metrics"><div><dt>CPU</dt><dd>${Number.isFinite(t.cpu?.usagePercent)?esc(t.cpu.usagePercent.toFixed(1))+'%':'Unknown'}</dd></div><div><dt>Memory</dt><dd>${bytes(t.memory?.usedBytes)} / ${bytes(t.memory?.totalBytes)}</dd></div><div><dt>Disk</dt><dd>${bytes(t.disk?.usedBytes)} / ${bytes(t.disk?.totalBytes)}<small>Free ${bytes(t.disk?.freeBytes)}</small></dd></div><div><dt>Uptime</dt><dd>${Number.isFinite(t.uptimeSeconds)?Math.floor(t.uptimeSeconds/3600)+'h '+Math.floor(t.uptimeSeconds%3600/60)+'m':'Unknown'}</dd></div></dl></div>`;};
const nodeRows=()=>city.nodes.map(n=>`<article class="device-card"><div class="row"><div class="node-info"><span class="node-icon">▣</span><div><button class="task-open" data-node="${esc(n.id)}">${esc(n.displayName)}</button><p class="muted">${esc(n.metadata?.platform)} · Agent ${esc(n.agentVersion||'Unknown')}</p><small>${connection==='ONLINE'?'':'Cached · '}Last seen ${esc(age(n.lastHeartbeatAt))}</small></div></div>${badge(nodeState(n))}</div>${metrics(n)}</article>`).join('')||'<p class="muted">Waiting for a runtime node.</p>';
const cityUrl=()=>{const e=city.descriptor?.endpoint;return e?e.scheme+'://'+e.host+':'+e.port:location.origin;};
function pairingView(){
 const d=city.discovery||{},remaining=pairing?Math.max(0,Math.ceil((Date.parse(pairing.expiresAt)-Date.now())/1000)):0;
 return `<section class="panel"><h2>Pair a device with ${esc(city.displayName||'your City')}</h2><p>City URL: ${esc(cityUrl())}</p><p class="task-id">City ID: ${esc(city.cityId||'Unknown')}</p><p>Current session: ${esc(pairing?.pairingSessionId||city.descriptor?.pairingSessionId||'None')}</p><p class="muted">${esc(pairingNotice)}</p>${pairing?`<div class="pairing-material"><div id="pairing-qr" role="img" aria-label="Temporary pairing QR"></div><div><p>Short pairing code</p><strong id="pairing-code">${esc(pairing.shortCode)}</strong><p id="pairing-countdown">Expires in ${remaining}s</p><p>Single use. Scan with Utopia on Android.</p></div></div>`:''}<button id="generate-pairing" ${connection!=='ONLINE'||pairingBusy?'disabled':''}>${pairing?'Revoke and refresh session':'Generate pairing session'}</button><p class="muted">Generating a session revokes the previous code and QR. Temporary pairing material is cleared when you leave this page.</p><h3>Connection diagnostics</h3><p>mDNS: ${esc(d.mdns?.state||'UNKNOWN')} · ${esc(d.mdns?.reason||'')}</p><p>Bluetooth: ${esc(d.ble?.state||'UNKNOWN')} · ${esc(d.ble?.reason||'')}</p><p>Gateway: ${esc(connection)} · apiVersion 0 · schemaVersion 0</p><h3>Choose a connection method</h3><ol><li><strong>QR:</strong> scan this temporary QR in the Android app.</li><li><strong>Nearby Cities (LAN):</strong> discover this City with mDNS, then enter the short code.</li><li><strong>Nearby via Bluetooth:</strong> find the nearby City, then enter the short code. Wi-Fi/LAN access is still required.</li><li><strong>Manual connection:</strong> enter the City URL and your existing control token in Android.</li></ol><p>Every method uses the same authenticated HTTP and WebSocket control connection.</p><p class="lan-warning">LAN DEVELOPMENT ONLY · NOT FOR PUBLIC INTERNET</p></section>`;
}
const events=list=>list.slice().reverse().map(e=>`<div class="event"><time>${esc(new Date(e.timestamp).toLocaleTimeString())}</time><strong>${esc(e.type)}</strong><div class="task-id">#${e.seq} · ${esc(e.taskId||'City')}</div></div>`).join('');
function render(){
 if(!city)return;$('#heading').textContent={Home:'Your city, at a glance.',Devices:'Your devices, in focus.',Pairing:'Bring a device into your city.',Tasks:'From intent to done.',Activity:'Life in your city.',Settings:'A connection you control.'}[page];$('#updated').textContent='Last snapshot · '+new Date(city.updatedAt).toLocaleTimeString();
 const t=city.tasks;
 if(page==='Home')$('#view').innerHTML=`<div class="stats">${[['Connected nodes',connection==='ONLINE'?city.nodes.filter(n=>n.online).length:'—'],['Running tasks',t.filter(t=>!finished(t)).length],['Completed tasks',t.filter(t=>t.state==='COMPLETED').length],['Needs attention',t.filter(t=>t.state==='FAILED').length]].map(([k,v])=>`<div class="card"><div class="stat-label">${k}</div><div class="stat-value">${v}</div></div>`).join('')}</div><div class="grid"><section class="panel"><h2>Runtime nodes</h2>${nodeRows()}</section><section class="panel"><h2>Recent activity</h2>${events(city.events.slice(-4))}</section></div><section class="panel" style="margin-top:22px"><h2>Recent tasks</h2>${taskRows(t.slice(-5))}</section>`;
 if(page==='Devices')$('#view').innerHTML=`<section class="panel">${nodeRows()}</section>`;
 if(page==='Tasks')$('#view').innerHTML=`<section class="panel"><h2>Task registry</h2>${taskRows(t)}</section>`;
 if(page==='Activity')$('#view').innerHTML=`<section class="panel"><h2>Event timeline · ${city.events.length} events</h2>${events(city.events)}</section>`;
 if(page==='Settings')$('#view').innerHTML=`<section class="panel"><h2>Connection diagnostics</h2><p>City URL: ${esc(location.origin)}</p><p>apiVersion = 0 · schemaVersion = 0</p><p>Pairing token is kept for this browser session.</p><button id="disconnect">Change pairing token</button></section>`;
 if(page==='Pairing'){$('#view').innerHTML=pairingView();if(pairing&&$('#pairing-qr'))$('#pairing-qr').innerHTML=pairing.qrSvg;}
 const detail=city.tasks.find(t=>t.id===selected);$('#detail').hidden=!detail;if(detail)$('#detail').innerHTML=`<h2>${esc(detail.type)}</h2><div class="task-id">${esc(detail.id)}</div><p>${badge(detail.state)} · ${esc(detail.assignedNodeId||'Waiting for node')}</p><progress max="100" value="${detail.progress}"></progress><h3>Checkpoint</h3><pre>${esc(JSON.stringify(detail.lastCheckpoint,null,2))}</pre><h3>Result</h3><pre>${esc(JSON.stringify(detail.result||detail.error,null,2))}</pre>${!finished(detail)?'<button id="cancel">Cancel task</button>':''}<h3>Task events</h3>${events(city.events.filter(e=>e.taskId===detail.id))}`;
 const device=city.nodes.find(n=>n.id===selectedNode);if(device){$('#detail').hidden=false;$('#detail').innerHTML=`<h2>${esc(device.displayName)}</h2><p>${badge(nodeState(device))} · ${esc(device.metadata?.platform)} · Agent ${esc(device.agentVersion||'Unknown')}</p><p class="task-id">${esc(device.id)}</p><p>Last seen ${esc(age(device.lastHeartbeatAt))}</p>${metrics(device)}<h3>Capabilities</h3><p>${esc(device.capabilities.join(' / '))}</p><h3>Current tasks</h3>${taskRows(t.filter(t=>t.assignedNodeId===device.id&&!finished(t)),'No active tasks.')}<h3>Recent device events</h3>${events(city.events.filter(e=>e.payload?.nodeId===device.id||t.some(t=>t.id===e.taskId&&t.assignedNodeId===device.id)).slice(-12))||'<p class="muted">No recent device events.</p>'}`;}
}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-page]'),task=e.target.closest('[data-task]'),node=e.target.closest('[data-node]');if(nav){clearPairing();page=nav.dataset.page;selected=null;selectedNode=null;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('selected',b===nav));render();}if(node){selectedNode=node.dataset.node;selected=null;render();$('#detail').scrollIntoView({behavior:'smooth'});}if(task){selectedNode=null;selected=task.dataset.task;render();$('#detail').scrollIntoView({behavior:'smooth'});}if(e.target.id==='generate-pairing'){const epoch=++pairingEpoch;pairingBusy=true;pairing=null;render();try{const result=await api('pairing/session',{});if(epoch===pairingEpoch&&page==='Pairing'&&connection==='ONLINE'){pairing=result;pairingNotice='';}}catch(err){$('#error').textContent=err.message;}finally{pairingBusy=false;render();}}if(e.target.id==='cancel'){try{await api('tasks/'+selected+'/cancel',{});await refresh();}catch(err){$('#error').textContent=err.message;}}if(e.target.id==='disconnect'){clearPairing();token='';$('#token').value='';sessionStorage.removeItem('city-token');++generation;clearTimeout(timer);ws?.close();$('#pair').hidden=false;$('#content').hidden=true;status('OFFLINE');}});
$('#connect').onclick=()=>{token=$('#token').value.trim();sessionStorage.setItem('city-token',token);$('#token').value='';connect();};
$('#run').onclick=async()=>{try{$('#run').disabled=true;const task=await api('tasks',{type:'CHECKPOINT_DEMO'});selectedNode=null;selected=task.id;await refresh();}catch(e){$('#error').textContent=e.message;}finally{$('#run').disabled=$('#connection').textContent!=='ONLINE';}};
window.addEventListener('offline',()=>{disconnected();ws?.close();});window.addEventListener('online',connect);
setInterval(()=>{if(token&&ws?.readyState===1)refresh().catch(e=>{disconnected(e);ws.close();});},4000);
setInterval(()=>{if(pairing&&Date.now()>=Date.parse(pairing.expiresAt)){clearPairing('Session expired. Generate a new session.');render();}else if(pairing&&$('#pairing-countdown'))$('#pairing-countdown').textContent='Expires in '+Math.max(0,Math.ceil((Date.parse(pairing.expiresAt)-Date.now())/1000))+'s';if(city&&(page==='Home'||page==='Devices'))render();},1000);
window.addEventListener('pagehide',()=>{clearPairing();render();});
document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('selected',b.dataset.page===page));
if(token)connect();else status('OFFLINE');
