import { t, applyTranslations, getLocale, setLocale, subscribe, formatTime, SUPPORTED_LOCALES, localeLabel } from './i18n/index.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token=sessionStorage.getItem('city-token')||'',city=null,page='Home',selected=null,ws,generation=0,timer,refreshing=false,pending=false,connection='OFFLINE';
const finished=t=>['COMPLETED','FAILED','CANCELLED'].includes(t.state);
async function api(path,body){const r=await fetch('/api/v0/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-City-Api-Version':'0','X-City-Schema-Version':'0'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(5000)});const x=await r.json();if(!r.ok)throw Error(x.error);if(x.apiVersion!==0||x.schemaVersion!==0)throw Error('Protocol mismatch: this client requires version 0');return x;}
// Connection state is protocol state, not copy: only the displayed label is localized.
function status(s){connection=s;const el=$('#connection');if(el){el.textContent=t('connection.'+s.toLowerCase());el.className=s==='ONLINE'?'online':'';}$('#run').disabled=s!=='ONLINE';render();}
function setError(message){$('#error').textContent=message||'';}
async function refresh(){if(refreshing){pending=true;return;}refreshing=true;try{city=await api('city');$('#pair').hidden=true;$('#content').hidden=false;setError('');render();}finally{refreshing=false;if(pending){pending=false;refresh().catch(disconnected);}}}
function disconnected(e){status('OFFLINE');if(e?.message)setError(e.message);}
async function connect(){const gen=++generation;clearTimeout(timer);ws?.close();status('RECONNECTING');try{await refresh();if(gen!==generation)return;ws=new WebSocket(location.origin.replace(/^http/,'ws')+'/api/v0/events/stream?apiVersion=0&schemaVersion=0',['city-v0','city-token.'+btoa(token).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')]);ws.onopen=()=>{if(gen===generation)status('ONLINE');};ws.onmessage=()=>refresh().catch(disconnected);ws.onerror=()=>disconnected();ws.onclose=()=>{if(gen===generation){disconnected();timer=setTimeout(connect,1800);}};}catch(e){if(gen===generation){disconnected(e);timer=setTimeout(connect,2500);}}}
const badge=s=>`<span class="badge ${esc(s)}">${esc(s)}</span>`;
const taskRows=tasks=>tasks.length?tasks.slice().reverse().map(x=>`<div class="row"><button class="task-open" data-task="${esc(x.id)}">${esc(x.type)}<div class="task-id">${esc(x.id)}</div></button>${badge(x.state)}</div>`).join(''):`<p class="muted">${esc(t('empty.noTasks'))}</p>`;
const nodeRows=()=>city.nodes.map(n=>`<div class="row"><div class="node-info"><span class="node-icon">▣</span><div><strong>${esc(n.displayName)}</strong><p class="muted">${esc(n.metadata.platform)} · ${esc(n.capabilities.join(' / '))}</p><small>${esc(t('task.heartbeat',{time:n.lastHeartbeatAt}))}</small></div></div>${badge(connection!=='ONLINE'?t('node.unknown'):n.online?t('node.online'):t('node.offline'))}</div>`).join('')||`<p class="muted">${esc(t('empty.waitingRuntimeNode'))}</p>`;
const events=list=>list.slice().reverse().map(e=>`<div class="event"><time>${esc(formatTime(e.timestamp))}</time><strong>${esc(e.type)}</strong><div class="task-id">#${e.seq} · ${esc(e.taskId||'City')}</div></div>`).join('');
// The Settings language control: switching rerenders, it never reloads or reconnects.
function languageSection(){const current=getLocale();return `<h2>${esc(t('settings.interface'))}</h2><p>${esc(t('settings.language'))}</p><div class="lang-row" id="language">${SUPPORTED_LOCALES.map(l=>`<button class="lang-option${l===current?' selected':''}" data-locale="${esc(l)}" aria-pressed="${l===current}">${esc(localeLabel(l))}</button>`).join('')}</div><p class="muted">${esc(t('settings.languageHint'))}</p>`;}
function render(){
 if(!city)return;$('#heading').textContent=t('heading.'+page.toLowerCase());$('#updated').textContent=t('status.lastSnapshot',{time:formatTime(city.updatedAt)});
 const tasks=city.tasks;
 if(page==='Home')$('#view').innerHTML=`<div class="stats">${[['stat.connectedNodes',connection==='ONLINE'?city.nodes.filter(n=>n.online).length:'—'],['stat.runningTasks',tasks.filter(x=>!finished(x)).length],['stat.completedTasks',tasks.filter(x=>x.state==='COMPLETED').length],['stat.needsAttention',tasks.filter(x=>x.state==='FAILED').length]].map(([k,v])=>`<div class="card"><div class="stat-label">${esc(t(k))}</div><div class="stat-value">${v}</div></div>`).join('')}</div><div class="grid"><section class="panel"><h2>${esc(t('section.runtimeNodes'))}</h2>${nodeRows()}</section><section class="panel"><h2>${esc(t('section.recentActivity'))}</h2>${events(city.events.slice(-4))}</section></div><section class="panel" style="margin-top:22px"><h2>${esc(t('section.recentTasks'))}</h2>${taskRows(tasks.slice(-5))}</section>`;
 if(page==='Nodes')$('#view').innerHTML=`<section class="panel">${nodeRows()}</section>`;
 if(page==='Tasks')$('#view').innerHTML=`<section class="panel"><h2>${esc(t('section.taskRegistry'))}</h2>${taskRows(tasks)}</section>`;
 if(page==='Activity')$('#view').innerHTML=`<section class="panel"><h2>${esc(t('section.eventTimeline',{count:city.events.length}))}</h2>${events(city.events)}</section>`;
 if(page==='Settings')$('#view').innerHTML=`<section class="panel">${languageSection()}<h2>${esc(t('section.connectionDiagnostics'))}</h2><p>${esc(t('settings.cityUrl'))}: ${esc(location.origin)}</p><p>${esc(t('settings.protocol',{api:0,schema:0}))}</p><p>${esc(t('settings.tokenNote'))}</p><button id="disconnect">${esc(t('settings.changeToken'))}</button></section>`;
 const detail=city.tasks.find(x=>x.id===selected);$('#detail').hidden=!detail;if(detail)$('#detail').innerHTML=`<h2>${esc(detail.type)}</h2><div class="task-id">${esc(detail.id)}</div><p>${badge(detail.state)} · ${esc(detail.assignedNodeId||t('status.waitingNode'))}</p><progress max="100" value="${detail.progress}"></progress><h3>${esc(t('section.checkpoint'))}</h3><pre>${esc(JSON.stringify(detail.lastCheckpoint,null,2))}</pre><h3>${esc(t('section.result'))}</h3><pre>${esc(JSON.stringify(detail.result||detail.error,null,2))}</pre>${!finished(detail)?`<button id="cancel">${esc(t('task.cancel'))}</button>`:''}<h3>${esc(t('section.taskEvents'))}</h3>${events(city.events.filter(e=>e.taskId===detail.id))}`;
}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-page]'),task=e.target.closest('[data-task]'),locale=e.target.closest('[data-locale]');if(nav){page=nav.dataset.page;selected=null;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('selected',b===nav));render();}if(task){selected=task.dataset.task;render();$('#detail').scrollIntoView({behavior:'smooth'});}if(locale){setLocale(locale.dataset.locale);}if(e.target.id==='cancel'){try{await api('tasks/'+selected+'/cancel',{});await refresh();}catch(err){setError(err.message);}}if(e.target.id==='disconnect'){token='';sessionStorage.removeItem('city-token');++generation;clearTimeout(timer);ws?.close();$('#pair').hidden=false;$('#content').hidden=true;status('OFFLINE');}});
// A locale change rerenders in place: no reconnect, no reload, no Gateway call.
subscribe(()=>{applyTranslations();render();});
$('#connect').onclick=()=>{token=$('#token').value.trim();sessionStorage.setItem('city-token',token);connect();};
$('#run').onclick=async()=>{try{$('#run').disabled=true;const task=await api('tasks',{type:'CHECKPOINT_DEMO'});selected=task.id;await refresh();}catch(e){setError(e.message);}finally{$('#run').disabled=$('#connection').textContent!==t('connection.online');}};
window.addEventListener('offline',()=>{disconnected();ws?.close();});window.addEventListener('online',connect);
setInterval(()=>{if(token&&ws?.readyState===1)refresh().catch(e=>{disconnected(e);ws.close();});},4000);
applyTranslations();
if(token)connect();else status('OFFLINE');
