import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {resolve} from 'node:path';import {createGateway} from '../services/dev-gateway/server.mjs';import {createHostJoin} from '../services/dev-gateway/host-join.mjs';import {readDeviceFile} from '../apps/client/device-enrollment.mjs';import {reserveHostCity,readHostCity} from '../services/dev-gateway/host-city.mjs';
const h={'Authorization':'Bearer remote-owner','X-City-Api-Version':'0','X-City-Schema-Version':'0','Content-Type':'application/json'};
test('joining only demotes the local host, saves its admission name and leaves remote City intact',async()=>{const dir=await mkdtemp(resolve('.scratch-role-'));let remote,reservation;try{remote=await createGateway({dir:resolve(dir,'remote'),port:0,token:'remote-owner',nodeToken:'remote-node'});reservation=await reserveHostCity({stateDir:resolve(dir,'host'),requestedDataDir:resolve(dir,'local'),coordinationPort:0});await reservation.publish({state:'ONLINE',role:'PRIMARY',cityId:'local-city',endpoint:'http://local'});const before=await readFile(resolve(dir,'host/city.json'),'utf8');const pair=await(await fetch(remote.url+'/api/v0/pairing/session',{method:'POST',headers:h,body:'{}'})).json();let transitions=0;
const broker=createHostJoin({localCityId:'local-city',localEndpoint:'http://127.0.0.1:1',deviceFile:resolve(dir,'device.json'),deviceId:'dev-11111111111111111111111111111111',transition:async record=>{transitions++;await reservation.publish({state:'ONLINE',role:'MEMBER',endpoint:record.endpoint,cityId:record.cityId});}});
const ticket=await broker.start({endpoint:remote.url,cityId:remote.store.cityId,mode:'code',shortCode:pair.shortCode,displayName:'用户命名电脑'});let state;for(let i=0;i<80;i++){state=await broker.status(ticket.ticketId);if(state.state==='JOINED')break;await new Promise(r=>setTimeout(r,25));}assert.equal(state.state,'JOINED',JSON.stringify(state));assert.equal(transitions,1);assert.equal(readDeviceFile(resolve(dir,'device.json')).displayName,'用户命名电脑');assert.equal((await readHostCity(reservation.coordinationPort)).role,'MEMBER');assert.equal(await readFile(resolve(dir,'host/city.json'),'utf8'),before);assert.equal((await(await fetch(remote.url+'/api/v0/city',{headers:h})).json()).cityId,remote.store.cityId);assert.ok(!JSON.stringify(state).includes('credentialSecret'));
}finally{await remote?.close();await reservation?.close();await rm(dir,{recursive:true,force:true});}});
test('failed pairing and busy local work do not demote or write a new membership',async()=>{const dir=await mkdtemp(resolve('.scratch-role-refusal-'));let remote;try{remote=await createGateway({dir:resolve(dir,'remote'),port:0,token:'remote-owner',nodeToken:'remote-node'});let changed=false;const deviceFile=resolve(dir,'device.json');const broker=createHostJoin({localCityId:'local',deviceFile,deviceId:'dev-11111111111111111111111111111111',transition:async()=>{changed=true;}});const ticket=await broker.start({endpoint:remote.url,mode:'code',shortCode:'000000',displayName:'本机'});let state;for(let i=0;i<80;i++){state=await broker.status(ticket.ticketId);if(state.state==='FAILED')break;await new Promise(r=>setTimeout(r,25));}assert.equal(state.state,'FAILED');assert.equal(changed,false);assert.equal(readDeviceFile(deviceFile),null);const busy=createHostJoin({localCityId:'local',deviceFile,deviceId:'dev-11111111111111111111111111111111',canJoin:()=>false,transition:async()=>{changed=true;}});await assert.rejects(busy.start({endpoint:remote.url,mode:'request',displayName:'x'}),/active local tasks/);
}finally{await remote?.close();await rm(dir,{recursive:true,force:true});}});

test('native production transition retires only local Gateway and its worker, while remote host stays primary',async()=>{
 const {demoteLocalHost}=await import('../services/dev-gateway/member-runtime.mjs');const {startAgent}=await import('../agents/reference-node/agent.mjs');const {Store}=await import('../services/dev-gateway/store.mjs');const dir=await mkdtemp(resolve('.scratch-real-demote-'));let local,remote,localAgent,member,reservation;try{
 remote=await createGateway({dir:resolve(dir,'remote'),port:0,token:'remote-owner',nodeToken:'remote-node'});reservation=await reserveHostCity({stateDir:resolve(dir,'registry'),requestedDataDir:resolve(dir,'local'),coordinationPort:0});let broker;local=await createGateway({dir:resolve(dir,'local'),port:0,token:'local-owner',nodeToken:'local-node',hostJoin:{start:input=>broker.start(input),status:id=>broker.status(id)}});const localId=local.store.cityId;const localUrl=local.url;const deviceId='dev-'+localId.replaceAll('-','');localAgent=await startAgent({url:local.url,token:'local-node',id:deviceId,displayName:'Local primary',workspace:resolve(dir,'old-worker'),interval:80,stepDelay:10});await reservation.publish({role:'PRIMARY',state:'ONLINE',cityId:localId,endpoint:local.url});broker=createHostJoin({localCityId:localId,localEndpoint:local.url,deviceFile:resolve(dir,'native.json'),deviceId,transition:async record=>{const result=await demoteLocalHost({record,app:local,agent:localAgent,reservation,workspace:resolve(dir,'member-worker'),retireDelay:150});member=result.agent;await result.retired;}});
 const pair=await(await fetch(remote.url+'/api/v0/pairing/session',{method:'POST',headers:h,body:'{}'})).json();const ticket=await broker.start({endpoint:remote.url,cityId:remote.store.cityId,mode:'code',shortCode:pair.shortCode,displayName:'My admitted host'});let state;for(let i=0;i<80;i++){state=await broker.status(ticket.ticketId);if(state.state==='JOINED')break;await new Promise(r=>setTimeout(r,30));}assert.equal(state.state,'JOINED',JSON.stringify(state));await assert.rejects(fetch(localUrl+'/api/v0/pairing/info'));const target=await(await fetch(remote.url+'/api/v0/city',{headers:h})).json();assert.ok(target.members.some(m=>m.deviceId===deviceId&&m.role==='MEMBER'&&m.computeOnline&&m.displayName==='My admitted host'));assert.ok(target.members.some(m=>m.deviceId===target.hostDeviceId&&m.role==='PRIMARY'));const saved=new Store(resolve(dir,'local'));assert.equal(saved.cityId,localId);saved.close();assert.equal((await readHostCity(reservation.coordinationPort)).role,'MEMBER');
 }finally{await member?.stop();await localAgent?.stop();await local?.close();await remote?.close();await reservation?.close();await rm(dir,{recursive:true,force:true});}
});

test('selected MEMBER role survives coordinator crash without replacing the original City pointer',async()=>{const dir=await mkdtemp(resolve('.scratch-role-persist-'));let reservation;try{reservation=await reserveHostCity({stateDir:dir,coordinationPort:0});await reservation.publish({role:'MEMBER',state:'ONLINE',cityId:'remote',endpoint:'http://remote',memberEnrollmentFile:resolve(dir,'device.json')});await reservation.close();reservation=await reserveHostCity({stateDir:dir,coordinationPort:0});assert.equal(reservation.selection.role,'MEMBER');assert.equal(reservation.selection.memberEnrollmentFile,resolve(dir,'device.json'));
}finally{await reservation?.close();await rm(dir,{recursive:true,force:true});}});
