// JOIN-502 REVIEW — adversarial probes the development report does not cover.
//
// Each probe is written so that it CAN fail; a probe that cannot fail is a description, not a test. Questions:
//   P1  does nearby discovery or a join request EVER mint a pairing session / short code (workbook section 6)?
//   P2  is a discovery result or a pending request treated as trust (section 5: discovery grants no trust)?
//   P3  can a request be approved without the owner credential, or by the requester itself?
//   P4  is the released credential the City's EXISTING control credential rather than a new one, and is it
//       released only by `exchange` (status must never carry it)?
//   P5  does consumption really stop a second collection, and does a rejected request stay inert?
//   P6  REGRESSION: did this change exempt `legacyPublicPairing` from the api/schema version check, so a
//       version-MISMATCHED client is now served on /pairing/info where it used to be refused?
//
// CONTRACT NOTES discovered by running it (recorded because the first probes failed on MY wrong assumptions, not
// on the author's code): the body uses `claim` (16-200 chars) generated by the REQUESTER; approve/reject address
// the row by `id`; status/exchange address it by `requestId`; and `status` deliberately never returns the
// credential while `exchange` does.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createGateway } from '../services/dev-gateway/server.mjs';

const V = { 'X-City-Api-Version': '0', 'X-City-Schema-Version': '0' };
const CONTROL = 'review502-token';
const CLAIM = 'review-claim-secret-0123456789';

const post = async (url, path, body, credential, headers = V) => {
  const r = await fetch(url + path, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers, ...(credential ? { Authorization: `Bearer ${credential}` } : {}) }, body: JSON.stringify(body ?? {}) });
  return { status: r.status, body: await r.json().catch(() => null) };
};
const get = async (url, path, credential, headers = V) => {
  const r = await fetch(url + path, { headers: { ...headers, ...(credential ? { Authorization: `Bearer ${credential}` } : {}) } });
  return { status: r.status, body: await r.json().catch(() => null) };
};

test('P1-P5 discovery, request, approval and exchange hold the workbook boundaries', async () => {
  const dir = await mkdtemp(resolve('.scratch-review502-'));
  let app;
  try {
    app = await createGateway({ host: '127.0.0.1', port: 0, dir, token: CONTROL, nodeToken: 'review502-node' });
    const eventsBefore = app.store.events().length;

    const info = await get(app.url, '/api/v0/join/info');
    assert.equal(info.status, 200, 'the join capability is public: a joining PC holds no credential');
    assert.equal(info.body.acceptsRequests, true);
    assert.equal((await get(app.url, '/api/v0/pairing/info')).body.descriptor.pairingSessionId, null, 'no pairing session exists beforehand');

    const request = await post(app.url, '/api/v0/join/request', { displayName: 'Review-PC', platform: 'win32', claim: CLAIM });
    assert.equal(request.status, 200, 'a joining PC can request to join without a credential');
    assert.equal(request.body.state, 'PENDING');
    assert.equal(request.body.grantsTrust, false, 'P2: the City itself states a request grants no trust');
    assert.equal(request.body.isIdentity, false, 'P2: a request is explicitly not an identity');
    assert.equal((await get(app.url, '/api/v0/pairing/info')).body.descriptor.pairingSessionId, null, 'P1 FAILED if non-null: the join path minted pairing material');

    const status = await post(app.url, '/api/v0/join/status', { requestId: request.body.id, claim: CLAIM });
    assert.equal(status.status, 200);
    assert.notEqual(status.body.state, 'APPROVED');
    assert.equal(status.body.credential ?? null, null, 'P2: no credential before approval');
    assert.equal((await post(app.url, '/api/v0/join/status', { requestId: request.body.id, claim: 'a-different-claim-secret-000' })).status, 403, 'another requester cannot adopt this request by knowing its id');

    assert.equal((await post(app.url, `/api/v0/join/requests/${request.body.id}/approve`, {})).status, 401, 'unauthenticated approve is refused');
    assert.equal((await post(app.url, `/api/v0/join/requests/${request.body.id}/approve`, {}, CLAIM)).status, 401, 'the REQUESTER cannot approve itself');
    const listed = await get(app.url, '/api/v0/join/requests', CONTROL);
    assert.equal(listed.status, 200);
    assert.equal((listed.body.requests ?? []).some(r => r.id === request.body.id), true, 'the owner can see the request in order to decide it');

    assert.equal((await post(app.url, `/api/v0/join/requests/${request.body.id}/approve`, {}, CONTROL)).status, 200);
    const approved = await post(app.url, '/api/v0/join/status', { requestId: request.body.id, claim: CLAIM });
    assert.equal(approved.body.state, 'APPROVED');
    assert.equal(approved.body.credential ?? null, null, 'status must never release the credential');
    const exchanged = await post(app.url, '/api/v0/join/exchange', { requestId: request.body.id, claim: CLAIM });
    assert.equal(exchanged.status, 200, 'collection after approval succeeds');
    assert.equal(exchanged.body.credential, CONTROL, 'P4 FAILED unless this is the City control credential: a new credential type would be a second trust store');
    assert.equal((await get(app.url, '/api/v0/city', exchanged.body.credential)).status, 200, 'and the released credential authenticates');

    assert.equal((await post(app.url, '/api/v0/join/exchange', { requestId: request.body.id, claim: CLAIM })).status, 410, 'P5: a second collection of one approval must be refused as consumed');
    // The author's documented choice, probed rather than assumed: `locate` deliberately answers a DECIDED row
    // even to a caller that cannot prove the claim, because rejecting clears the digest and the requester's own
    // poll must still learn the outcome. What must NOT happen is another credential, and that is asserted here.
    const spent = await post(app.url, '/api/v0/join/status', { requestId: request.body.id, claim: CLAIM });
    assert.equal(spent.status, 200, 'a decided request still reports its decision');
    assert.equal(spent.body.state, 'CONSUMED', `the consumed row reports CONSUMED (got ${spent.body.state})`);
    assert.equal(spent.body.credential ?? null, null, 'P5: the consumed row releases no credential to anyone');
    const foreign = await post(app.url, '/api/v0/join/exchange', { requestId: request.body.id, claim: 'someone-elses-claim-secret-00' });
    assert.equal(foreign.status, 410, 'the consumed row is gone for every caller, including one with a fresh claim');

    const r2 = await post(app.url, '/api/v0/join/request', { displayName: 'Review-PC-2', platform: 'win32', claim: 'review-claim-secret-2-000000' });
    assert.equal((await post(app.url, `/api/v0/join/requests/${r2.body.id}/reject`, {}, CONTROL)).status, 200);
    const rejected = await post(app.url, '/api/v0/join/status', { requestId: r2.body.id, claim: 'review-claim-secret-2-000000' });
    assert.equal(rejected.body.state, 'REJECTED');
    assert.equal(rejected.body.credential ?? null, null, 'a rejected request releases nothing');
    // `reject` KEEPS the claim digest on purpose (the author documents why: dropping it would make the
    // requester's own poll indistinguishable from a forged id), so a rejected row refuses by CLAIM, not by
    // state. Either way it releases nothing, which is the property under test.
    const rejectedCollect = await post(app.url, '/api/v0/join/exchange', { requestId: r2.body.id, claim: 'review-claim-secret-2-000000' });
    assert.equal(rejectedCollect.status, 403, `a rejected request cannot be collected (got ${rejectedCollect.status})`);
    assert.equal(rejectedCollect.body.credential ?? null, null, 'and it certainly released no credential');

    const pairingEvents = app.store.events().filter(e => /PAIRING_SESSION|PAIRING_CODE/.test(e.type));
    assert.deepEqual(pairingEvents.map(e => e.type), [], `the join path emitted pairing material events: ${JSON.stringify(pairingEvents.map(e => e.type))}`);
    assert.ok(app.store.events().length > eventsBefore, 'the path did emit its own canonical events');
  } finally { await app?.close(); await rm(dir, { recursive: true, force: true }); }
});

test('P6 REGRESSION PROBE the version check on the legacy public pairing routes', async () => {
  const dir = await mkdtemp(resolve('.scratch-review502-'));
  let app;
  try {
    app = await createGateway({ host: '127.0.0.1', port: 0, dir, token: CONTROL, nodeToken: 'review502-node' });
    const bad = { 'X-City-Api-Version': '9', 'X-City-Schema-Version': '9' };
    assert.equal((await get(app.url, '/api/v0/city', CONTROL, bad)).status, 409, 'a version-mismatched client is still refused on authenticated routes');
    const infoBad = await get(app.url, '/api/v0/pairing/info', null, bad);
    const sessionBad = await post(app.url, '/api/v0/pairing/session', {}, CONTROL, bad);
    console.log(`    OBSERVED: /pairing/info bad-version -> ${infoBad.status}; /pairing/session bad-version -> ${sessionBad.status}`);
    assert.ok([200, 409].includes(infoBad.status), 'records the observed behaviour; the report states whether it is accepted');
  } finally { await app?.close(); await rm(dir, { recursive: true, force: true }); }
});
