import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createGateway} from '../services/dev-gateway/server.mjs';
import {chromium} from 'playwright';
const fixture=async(fn)=>{const dir=await mkdtemp(resolve('.scratch-mon990-'));const app=await createGateway({dir,port:0,token:'monitor-owner',nodeToken:'monitor-node',roomsDisabled:true});const api=async(path,body)=>{const r=await fetch(app.url+'/api/v0/'+path,{headers:{Authorization:'Bearer monitor-owner','Content-Type':'application/json','X-City-Api-Version':'0','X-City-Schema-Version':'0'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};try{await fn(app,api)}finally{await app.close();await rm(dir,{recursive:true,force:true})}};
test('MON990: decision projection binds canonical City and graph/decision failures do not stop task creation',()=>fixture(async(app,api)=>{assert.equal((await api('monitor/decisions')).data.cityId,app.store.cityId);const refresh=app.observation.refresh;app.observation.refresh=async()=>{throw Error('CONTROLLED_OBSERVER_UNAVAILABLE')};try{assert.equal((await api('monitor/graph')).status,500);const created=await api('tasks',{type:'WAIT'});assert.equal(created.status,200);assert.equal(app.store.get('tasks',created.data.id).state,'QUEUED');assert.equal((await api('monitor/decisions')).status,200)}finally{app.observation.refresh=refresh}}));
test('MON990: overview has a working contextual link to advisory decision provenance',()=>fixture(async(app)=>{const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});try{const page=await browser.newPage({locale:'en-US'});await page.goto(app.url);await page.locator('#token').fill('monitor-owner');await page.locator('#connect').click();await page.locator('#connection.online').waitFor();await page.locator('nav [data-page="Monitor"]').click();await page.locator('.monitor-panel[data-loaded="true"]').waitFor();await page.locator('#view [data-page="Decisions"]').click({timeout:3000});await page.locator('#monitor-decisions').waitFor();assert.match(await page.locator('#monitor-decisions').innerText(),/decision provenance|decisions/i)}finally{await browser.close()}}));
