import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium} from 'playwright';
import {createGateway} from '../services/dev-gateway/server.mjs';
import {startAgent} from '../agents/reference-node/agent.mjs';
import {registerNode} from '../scripts/agent-job.mjs';
const owner='draft-owner',nodeToken='draft-node';
const H={'X-City-Api-Version':'0','X-City-Schema-Version':'0',Authorization:'Bearer '+owner,'Content-Type':'application/json'};
test('Web Ask drafts open the real forms, preserve edits and invalidate old confirmations', {timeout:90000},async t=>{
 const dir=await mkdtemp(resolve('.scratch-owner-draft-web-'));
 const app=await createGateway({dir:resolve(dir,'city'),port:0,token:owner,nodeToken,roomsDisabled:true,heartbeatTimeout:60000,remoteOperation:{enabled:true,allowlist:['node'],workspaces:[dir]},agentJob:{enabled:true}});
 const agent=await startAgent({url:app.url,token:nodeToken,id:'dev-alien',displayName:'Alien',workspace:resolve(dir,'agent'),interval:80,stepDelay:10});
 await registerNode({url:app.url,token:nodeToken,id:'dev-review',displayName:'Review Agent'});
 const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
 t.after(async()=>{await browser.close();await agent.stop();await app.close();await rm(dir,{recursive:true,force:true,maxRetries:12,retryDelay:60});});
 const page=await browser.newPage({locale:'en-US'});page.setDefaultTimeout(15000);
 await page.goto(app.url);await page.locator('#token').fill(owner);await page.locator('#connect').click();await page.locator('#connection.online').waitFor();
 const say=async text=>{await page.locator('#ask-text').fill(text);await page.locator('#ask-submit').click();await page.locator('[data-terminal="ask-owner-draft"]').waitFor();};
 await say('run node on Alien; argv ["-e", "process.stdout.write(\'draft-ok\')"]');
 assert.equal((await (await fetch(app.url+'/api/v0/tasks',{headers:H})).json()).tasks.length,0);
 await page.locator('[data-terminal="ask-owner-draft"]').click();await page.locator('#rop-refresh').waitFor();
 await page.waitForFunction(()=>document.querySelector('#rop-node')?.value==='dev-alien');
 assert.equal(await page.locator('#rop-executable').inputValue(),'node');
 await page.locator('#rop-cwd').fill(dir);await page.locator('#rop-purpose').fill('observe a confirmed draft execution');
 await page.locator('#rop-danger > summary').click();await page.locator('#rop-confirm').fill('node');
 assert.equal(await page.locator('#rop-dispatch').isDisabled(),false);
 await page.locator('#rop-purpose').fill('updated explicit purpose');
 assert.equal(await page.locator('#rop-confirm').inputValue(),'');assert.equal(await page.locator('#rop-dispatch').isDisabled(),true);
 await page.locator('#rop-confirm').fill('node');await page.locator('#rop-dispatch').click();
 await page.waitForFunction(()=>document.querySelector('#rop-list')?.textContent?.includes('draft-ok'));
 assert.equal(await page.locator('#rop-purpose').inputValue(),'updated explicit purpose','refresh must not replay the original seed');
 await say('ask the Agent on Review to inspect the tests');
 await page.locator('[data-terminal="ask-owner-draft"]').click();await page.locator('#aj-refresh').waitFor();
 await page.locator('#aj-node').selectOption('dev-review');await page.locator('#aj-title').fill('Review current tests');
 await page.locator('#aj-instruction').fill('Inspect current test evidence and report observations.');await page.locator('#aj-purpose').fill('validate the user job flow');
 await page.locator('#aj-danger > summary').click();await page.locator('#aj-confirm').fill('Review current tests');
 await page.locator('#aj-instruction').fill('Inspect the updated test evidence.');
 assert.equal(await page.locator('#aj-confirm').inputValue(),'');assert.equal(await page.locator('#aj-dispatch').isDisabled(),true);
 await page.locator('#aj-confirm').fill('Review current tests');await page.locator('#aj-dispatch').click();
 await page.waitForFunction(()=>document.querySelector('#aj-list')?.textContent?.includes('Review current tests'));
 const tasks=(await (await fetch(app.url+'/api/v0/tasks',{headers:H})).json()).tasks;assert.equal(tasks.length,2);
 assert.equal(tasks.find(t=>t.type==='OWNER_REMOTE_OPERATION').state,'COMPLETED');assert.equal(tasks.find(t=>t.type==='AGENT_JOB').targetDeviceRef,'dev-review');
});
