import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Store} from '../services/dev-gateway/store.mjs';import {createCanonicalStateAdapter} from '../services/personal-compute-fabric/canonical-state-adapter.mjs';import {createArtifactStore} from '../services/personal-compute-fabric/artifacts.mjs';import {executeApprovedLocal} from '../services/personal-compute-fabric/local-flow.mjs';import {projectOrigin} from '../services/personal-compute-fabric/origin-projection.mjs';import {createOriginAgentBridge} from '../services/personal-compute-fabric/origin-agent-bridge.mjs';
test('full local candidate: two real CPU applications execute through canonical admission/artifacts/capsule/receipt/origin/consumption',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'pcf-flow-')),store=new Store(dir);try{
 const owner=createCanonicalStateAdapter(store),artifacts=createArtifactStore({root:join(dir,'artifacts'),maxBytes:1048576,maxItems:16,authorize:({metadata,context,operation})=>operation==='PUBLISH'||metadata.owner===context.caller});
 const now=Date.now(),authority={version:1,authorized:true,expiresAt:now+60000,originDeviceId:'local-alien',allowedDevices:['local-alien'],dataScopes:['PUBLIC'],sharingConsent:false,cloudConsent:false,budget:0};
 const workloads=['SORT','SUM'].map((operation,i)=>({version:1,taskId:'T'+i,actionId:'A'+i,originDeviceId:'local-alien',parentSessionId:'session-local',appId:operation,kind:'CPU_JSON',capabilities:['cpu.json'],resources:{cpu:1,memory:1024*1024},dataScope:'PUBLIC',qos:i?'BATCH':'INTERACTIVE',retryClass:'PURE',inputRefs:[],writeScope:[],outputSchema:'json',deadlineAt:now+60000}));
 for(const w of workloads){store.put('tasks',{id:w.taskId,actionId:w.actionId,originDeviceId:w.originDeviceId,parentSessionId:w.parentSessionId,state:'QUEUED'});store.put('actions',{id:w.actionId,taskId:w.taskId});}
 const results=await Promise.all(workloads.map((w,i)=>executeApprovedLocal({owner,artifacts,workload:w,input:{operation:i?'SUM':'SORT',values:[4,1,3,2]},authority,deviceId:'local-alien'})));
 assert.deepEqual(results[0].output.values,[1,2,3,4]);assert.equal(results[1].output.sum,10);assert.notEqual(results[0].receipt.pid,results[1].receipt.pid);assert.equal(owner.snapshot().reservations.length,0);
 const ctx={authorized:true,sessionId:'session-local',deviceId:'local-alien'};for(const w of workloads){assert.equal(projectOrigin(store.get('tasks',w.taskId),[],{auth:ctx,after:0}).state,'COMPLETED');}
 const bridge=createOriginAgentBridge({submit:async()=>{},get:async id=>store.get('tasks',id),cancel:async()=>{},markConsumed:async(id,c,digest)=>store.atomic(()=>{const t=store.get('tasks',id);assert.equal(t.pcfResult.digest,digest);return store.put('tasks',{...t,pcfConsumedSessionId:c.sessionId});})},{authorize:async c=>c.sessionId===ctx.sessionId&&c.deviceId===ctx.deviceId});
 const delivery=await bridge.collect('T0',ctx);assert.equal(delivery.consumed,false);await bridge.acknowledge('T0',ctx,delivery.result.digest);assert.equal((await bridge.collect('T0',ctx)).consumed,true);
 }finally{store.db.close();await rm(dir,{recursive:true,force:true});}
});
