import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {Store} from '../services/dev-gateway/store.mjs';import {createFabricService} from '../services/personal-compute-fabric/service.mjs';
const context={sessionId:'session',deviceId:'alien'};
async function withService(fn){const dir=await mkdtemp(join(tmpdir(),'pcf-service-')),store=new Store(dir);let authorized=true;const service=createFabricService({store,artifactRoot:join(dir,'artifacts'),deviceId:'alien',readAuthority:async c=>({version:1,authorized:authorized&&c.sessionId===context.sessionId&&c.deviceId===context.deviceId,expiresAt:Date.now()+60000,originDeviceId:'alien',allowedDevices:['alien'],dataScopes:['PUBLIC'],sharingConsent:false,cloudConsent:false,budget:0}),maxParallel:2});try{await fn(service,store,()=>{authorized=false;});}finally{await service.stop();store.db.close();await rm(dir,{recursive:true,force:true});}}
test('approved service creates one existing canonical task/action, starts independently of UI and returns once to bound caller',()=>withService(async(service,store)=>{
 const request={appId:'cpu-sort',idempotencyKey:'sort-1',input:{values:[4,2,1]},parentSessionId:'session'};
 const first=await service.submit(request,context);const replay=await service.submit(request,context);assert.equal(first.taskId,replay.taskId);assert.equal(store.list('tasks').length,1);assert.equal(store.list('actions').length,1);
 await service.start();await service.waitForIdle();const task=store.get('tasks',first.taskId);assert.equal(task.state,'COMPLETED');assert.ok(task.pcfProcessIdentity.pid>0);assert.equal(store.get('actions',first.actionId).status,'SUCCEEDED');
 const result=await service.collect(first.taskId,context);assert.deepEqual(result.output.values,[1,2,4]);assert.equal(result.consumed,false);await service.acknowledge(first.taskId,context,result.digest);assert.equal((await service.collect(first.taskId,context)).consumed,true);
 await assert.rejects(()=>service.collect(first.taskId,{...context,sessionId:'other'}));await assert.rejects(()=>service.submit({...request,input:{values:[99]}},context));
}));
test('service bounds queue, rejects unapproved/cross-device work, drains and preserves cancel terminal truth',()=>withService(async(service,store,revoke)=>{
 await assert.rejects(()=>service.submit({appId:'shell',idempotencyKey:'x',input:{}},context));await assert.rejects(()=>service.submit({appId:'cpu-sum',idempotencyKey:'x',parentSessionId:'session',input:{values:[1]},strictTargetDeviceId:'mech'},context));
 const one=await service.submit({appId:'cpu-sum',idempotencyKey:'sum',parentSessionId:'session',input:{values:[1,2]}},context);await service.cancel(one.taskId,context);await service.start();await service.waitForIdle();assert.equal(store.get('tasks',one.taskId).state,'CANCELLED');await service.drain();await assert.rejects(()=>service.submit({appId:'cpu-sum',idempotencyKey:'new',parentSessionId:'session',input:{values:[1]}},context));
 revoke();await assert.rejects(()=>service.inspect(one.taskId,context));
}));
test('live policy revocation before dispatch prevents a process launch and does not invent side effects',()=>withService(async(service,store,revoke)=>{const job=await service.submit({appId:'cpu-sum',idempotencyKey:'revoke',parentSessionId:'session',input:{values:[1]}},context);revoke();await service.start();await service.waitForIdle();const task=store.get('tasks',job.taskId);assert.equal(task.state,'FAILED');assert.equal(task.pcfAttention,'AUTHORITY_EXPIRED_OR_REVOKED');assert.equal(task.pcfResult?.pid??null,null);}));

test('a second supervisor cannot take ownership merely because time elapsed',()=>withService(async(service,store)=>{const second=createFabricService({store,artifactRoot:join(store.dir??'.runtime','unused-artifacts'),deviceId:'alien',readAuthority:async()=>({})});await service.start();await assert.rejects(()=>second.start(),{code:'SUPERVISOR_OWNERSHIP_UNKNOWN'});await second.stop();assert.equal(service.health().state,'RUNNING');}));

test('drain fences an admission awaiting current authority and creates no late Task or Action',async()=>{const dir=await mkdtemp(join(tmpdir(),'pcf-drain-race-'));const store=new Store(dir);let release,entered;const blocked=new Promise(r=>{release=r;}),seen=new Promise(r=>{entered=r;});const service=createFabricService({store,artifactRoot:join(dir,'artifacts'),deviceId:'alien',readAuthority:async()=>{entered();await blocked;return {version:1,authorized:true,expiresAt:Date.now()+60000,originDeviceId:'alien',allowedDevices:['alien'],dataScopes:['PUBLIC'],budget:0};}});try{const pending=service.submit({appId:'cpu-sum',idempotencyKey:'late',parentSessionId:'session',input:{values:[1]}},context);await seen;await service.drain();release();await assert.rejects(()=>pending,{code:'FABRIC_DRAINING'});assert.equal(store.list('tasks').length,0);assert.equal(store.list('actions').length,0);}finally{release();await service.stop();store.db.close();await rm(dir,{recursive:true,force:true});}});
