import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createGateway} from '../services/dev-gateway/server.mjs';
async function fixture(pcf,run){const dir=await mkdtemp(join(tmpdir(),'pcf-gateway-'));let gateway;try{gateway=await createGateway({dir,port:0,token:'owner-test',nodeToken:'node-test',hostDeviceId:'local-test',roomsDisabled:true,pcf});const call=async(path,body,extra={})=>{const response=await fetch(gateway.url+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer owner-test','x-city-api-version':'0','x-city-schema-version':'0','content-type':'application/json',...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,data:await response.json()};};await run(gateway,call);}finally{await gateway?.close();await rm(dir,{recursive:true,force:true});}}
test('default gateway retains readonly fabric and does not admit PCF jobs',()=>fixture(undefined,async(g,call)=>{assert.equal((await call('/api/v0/pcf')).status,200);assert.equal((await call('/api/v0/pcf/submit',{appId:'cpu-sort'})).status,404);assert.equal(g.pcf,null);}));
test('explicit approved local owner executes CPU and acknowledges digest',()=>fixture({enabled:true,approvedLocalContext:{deviceId:'local-test'}},async(g,call)=>{const info=await call('/api/v0/pcf');assert.ok(info.data.parentSessionId);const accepted=await call('/api/v0/pcf/submit',{appId:'cpu-sort',idempotencyKey:'one',input:{values:[3,1,2]}});assert.equal(accepted.status,200);await g.pcf.waitForIdle();const id=accepted.data.taskId;assert.equal((await call('/api/v0/pcf/tasks/'+id)).data.task.state,'COMPLETED');const result=await call('/api/v0/pcf/tasks/'+id+'/collect',{});assert.deepEqual(result.data.output.values,[1,2,3]);assert.equal((await call('/api/v0/pcf/tasks/'+id+'/acknowledge',{digest:result.data.digest})).data.consumed,true);assert.equal((await call('/api/v0/pcf/submit',{appId:'cpu-sort',idempotencyKey:'spoof',input:{values:[]},parentSessionId:'forged'})).status,403);assert.equal((await call('/api/v0/pcf/submit',{appId:'cpu-sort',idempotencyKey:'origin',input:{values:[]}},{origin:'https://untrusted.example'})).status,403);assert.equal((await call('/api/v0/pcf/submit',{}, {authorization:'Bearer node-test'})).status,401);}));
test('enabled without approved device refuses startup',async()=>{const dir=await mkdtemp(join(tmpdir(),'pcf-config-'));try{await assert.rejects(()=>createGateway({dir,port:0,token:'a',nodeToken:'b',pcf:{enabled:true}}),/PCF_LOCAL_APPROVAL/);}finally{await rm(dir,{recursive:true,force:true});}});

test('legacy cancellation cannot change PCF state and member session has no owner authority',()=>fixture({enabled:true,approvedLocalContext:{deviceId:'local-test'}},async(g,call)=>{await g.pcf.drain();const job=await call('/api/v0/pcf/submit',{appId:'cpu-sum',idempotencyKey:'queued',input:{values:[1]}});assert.equal(job.status,409);await g.pcf.start();const accepted=await call('/api/v0/pcf/submit',{appId:'cpu-sort',idempotencyKey:'cancel',input:{values:Array.from({length:1024},(_,i)=>1024-i)}});assert.equal((await call('/api/v0/tasks/'+accepted.data.taskId+'/cancel',{})).status,409);const enrollment=await call('/api/v0/device/enroll',{displayName:'member',platform:'win32'});const rec=enrollment.data;const opened=await call('/api/v0/device/session',{installationId:rec.installation.installationId,instanceId:rec.installation.instanceId,credentialId:rec.credential.credentialId,credentialSecret:rec.credential.credentialSecret});assert.equal((await call('/api/v0/pcf/tasks/'+accepted.data.taskId,undefined,{authorization:'Bearer '+opened.data.credential})).status,403);await g.pcf.waitForIdle();assert.equal((await call('/api/v0/pcf/tasks/'+accepted.data.taskId+'/cancel',{})).status,200);}));
