import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Store} from '../services/dev-gateway/store.mjs';import {createCanonicalStateAdapter} from '../services/personal-compute-fabric/canonical-state-adapter.mjs';import {admit,claimAttempt,commitResult} from '../services/personal-compute-fabric/admission.mjs';import {planPlacement} from '../services/personal-compute-fabric/placement.mjs';import {createArtifactStore} from '../services/personal-compute-fabric/artifacts.mjs';
const policy={version:1,authorized:true,originDeviceId:'alien',mode:'ORIGIN_DEVICE_ONLY',allowedDevices:['alien'],dataScopes:['PUBLIC'],sharingConsent:false,cloudConsent:false,budget:0,expiresAt:5000};
const w={taskId:'T',actionId:'A',originDeviceId:'alien',parentSessionId:'S',appId:'app',dataScope:'PUBLIC',kind:'CPU_JSON',capabilities:['cpu.json'],resources:{cpu:1,memory:10},deadlineAt:4000,writeScope:[],qos:'BATCH'};
const c={deviceId:'alien',bootId:'b',trusted:true,authorized:true,executorReady:true,sharing:true,platform:'win32',provider:{id:'cpu',ready:true,capabilities:['cpu.json'],workloadKinds:['CPU_JSON'],isolation:'COOPERATIVE'},observationVersion:1,observedAt:900,validUntil:3000,free:{cpu:2,memory:100},queueMs:0,cost:{inputMs:[0,1],coldStartMs:[0,1],executeMs:[0,1],returnMs:[0,1]}};
const request=workload=>({workload,proposal:planPlacement(workload,[c],policy,1000),policy,candidate:c,idempotencyKey:workload.taskId,ttlMs:1000,appQuota:{cpu:2,memory:100},now:1000});
test('review: canonical task ownership cannot be substituted by a caller workload',async()=>{const dir=await mkdtemp(join(tmpdir(),'pcf-victim-')),s=new Store(dir);try{s.put('tasks',{id:'T',state:'QUEUED',actionId:'VICTIM-A',originDeviceId:'VICTIM-D',parentSessionId:'VICTIM-S'});const owner=createCanonicalStateAdapter(s);assert.throws(()=>admit(owner,request(w)));assert.equal(owner.snapshot().reservations.length,0);}finally{s.db.close();await rm(dir,{recursive:true,force:true});}});
test('review: terminal attempt retention remains bounded without stopping job 257',async()=>{const dir=await mkdtemp(join(tmpdir(),'pcf-retention-')),s=new Store(dir);try{const owner=createCanonicalStateAdapter(s);for(let i=0;i<260;i++){const workload={...w,taskId:'T'+i,actionId:'A'+i};s.put('tasks',{id:workload.taskId,state:'QUEUED',actionId:workload.actionId,originDeviceId:'alien',parentSessionId:'S'});const r=admit(owner,request(workload)).reservation;const a=claimAttempt(owner,{reservationId:r.id,holder:'h',bootId:'b',now:1100});commitResult(owner,{taskId:workload.taskId,attemptId:a.id,epoch:a.epoch,holder:'h',bootId:'b',outcome:'SUCCEEDED',outputDigest:'a'.repeat(64),now:1200});}assert.ok(owner.snapshot().attempts.length<=128);assert.equal(s.get('tasks','T259').state,'SUCCEEDED');}finally{s.db.close();await rm(dir,{recursive:true,force:true});}});
test('review: separate artifact stores cannot acknowledge over-quota concurrent publications',async()=>{const dir=await mkdtemp(join(tmpdir(),'pcf-art-race-'));try{const a=createArtifactStore({root:dir,maxBytes:6,maxItems:1,authorize:()=>true}),b=createArtifactStore({root:dir,maxBytes:6,maxItems:1,authorize:()=>true});const args=[Buffer.from('123456'),{owner:'S',dataScope:'PUBLIC',expiresAt:5000},1000];const results=await Promise.allSettled([a.publish(...args),b.publish(...args)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const ref=results.find(r=>r.status==='fulfilled').value;assert.equal((await a.read(ref,{caller:'S'},1000)).toString(),'123456');}finally{await rm(dir,{recursive:true,force:true});}});
