import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../services/dev-gateway/store.mjs';
import {createCanonicalStateAdapter} from '../services/personal-compute-fabric/canonical-state-adapter.mjs';
import {createArtifactStore} from '../services/personal-compute-fabric/artifacts.mjs';
import {createHeadlessAgent} from '../services/headless-node-agent/agent.mjs';
import {createWorkerPoolBackend} from '../services/dev-gateway/execution-backend/worker-pool.mjs';
import {nodeDescriptor} from '../contracts/node-descriptor-v1/index.mjs';
const modulePath='../services/personal-compute-fabric/remote-worker-port.mjs';
async function fixture(run){const dir=await mkdtemp(join(tmpdir(),'pcf-remote-'));const store=new Store(dir);try{const module=await import(modulePath).catch(()=>({}));assert.equal(typeof module.createRemoteWorkerPort,'function','missing explicit remote worker canonical port');const owner=createCanonicalStateAdapter(store);let granted=true,ownerGranted=true,ownerVersion=1,workerVersion=1;const principals=['worker-a','worker-b'].map(deviceId=>({deviceId,bootId:'boot-'+deviceId,instanceId:'instance-'+deviceId}));const facts=()=>({version:ownerVersion,authorized:ownerGranted,expiresAt:Date.now()+60000,originDeviceId:'origin',allowedDevices:['origin',...principals.map(p=>p.deviceId)],dataScopes:['PUBLIC'],sharingConsent:true,cloudConsent:false,budget:0});const observations=()=>principals.map(p=>({...p,trusted:true,authorized:true,sharing:true,executorReady:true,platform:process.platform,provider:{id:'fixed-cpu',ready:true,capabilities:['cpu.json'],workloadKinds:['CPU_JSON']},free:{cpu:2,memory:10485760},observedAt:Date.now(),validUntil:Date.now()+20000,observationVersion:1}));const artifacts=createArtifactStore({root:join(dir,'artifacts'),maxBytes:16777216,maxItems:128,authorize:()=>true});const closed=new Map();const options={enabled:true,owner,taskFor:id=>store.get('tasks',id),readAuthority:facts,authorizeWorker:async p=>({authorized:granted,version:workerVersion,...p}),observations,artifacts,validateAuthorityBoundary:({policyVersion,grantVersion})=>granted&&ownerGranted&&(policyVersion===null||policyVersion===ownerVersion)&&grantVersion===workerVersion,verifyClosed:async receipt=>closed.get(receipt.attemptId)?.pid===receipt.pid};const port=module.createRemoteWorkerPort(options);const reopen=()=>module.createRemoteWorkerPort(options);async function dispatch(index){const id='task-'+index,deviceId=principals[index%2].deviceId;const ref=await artifacts.publish(Buffer.from(JSON.stringify({operation:'SORT',values:[9,2,index]})),{owner:'session',dataScope:'PUBLIC',expiresAt:Date.now()+60000},Date.now());const workload={version:1,taskId:id,actionId:'action-'+index,originDeviceId:'origin',parentSessionId:'session',appId:'cpu-sort',kind:'CPU_JSON',capabilities:['cpu.json'],resources:{cpu:1,memory:1024},dataScope:'PUBLIC',qos:'BATCH',retryClass:'PURE',inputRefs:[ref],writeScope:[],outputSchema:'json',deadlineAt:Date.now()+60000,strictTargetDeviceId:deviceId};store.put('tasks',{id,state:'QUEUED',executionBackendId:'pcf-v1',actionId:workload.actionId,originDeviceId:'origin',parentSessionId:'session',pcfAppId:'cpu-sort',targetDeviceRef:deviceId});return reopen().dispatch({endpointRef:deviceId,taskId:id,workload,idempotencyKey:id});}await run({module,store,owner,port,principals,closed,dispatch,reopen,options,revokeOwner:()=>{ownerGranted=false;ownerVersion++;},revoke:()=>{granted=false;workerVersion++;}});}finally{store.close();await rm(dir,{recursive:true,force:true});}}
test('opt-in canonical port uses two actual CPU processes through headless agents and WBC pool',()=>fixture(async({module,store,port,principals,closed,dispatch})=>{const descriptors=principals.map(p=>nodeDescriptor({nodeId:p.deviceId,displayName:p.deviceId,roles:['EXECUTION_NODE'],capabilities:['cpu.json'],availability:{acceptingWork:true,sharingEnabled:true}}));const pool=createWorkerPoolBackend({enabled:true,canonical:port,memberRefs:principals.map(p=>p.deviceId),descriptors:()=>descriptors,taskFor:id=>store.get('tasks',id)});const pids=[];await dispatch(0);await dispatch(1);for(const principal of principals){const request=module.createRemoteWorkerRequest({port:pool,canonical:port,authenticate:async()=>principal});const agent=createHeadlessAgent({identity:{id:principal.deviceId,displayName:principal.deviceId},capabilities:['cpu.json'],credentialHandle:'injected-existing-transport',request});await agent.register();const execute=module.createRemoteCpuExecutor({port,principal,onClosed:async receipt=>{closed.set(receipt.attemptId,receipt);pids.push(receipt.pid);}});const result=await agent.runOne(execute);assert.equal(result.state,'COMPLETED');assert.deepEqual((await port.collect(result.id,{sessionId:'session',deviceId:'origin'})).output.values,[principal.deviceId==='worker-a'?0:1,2,9]);}assert.equal(new Set(pids).size,2);assert.ok(pids.every(pid=>pid>0));assert.equal(port.evidenceClass,'SIMULATED_TOPOLOGY+ACTUAL_LOCAL_PROCESSES');}));
test('durable claim nonce, exact principal and current grant block replay or revoked worker',()=>fixture(async({port,principals,dispatch,revoke,store})=>{await dispatch(0);const claim=await port.claim({nodeId:'worker-a',principal:principals[0]});assert.ok(claim.task.pcfRemote.claimNonce);await assert.rejects(()=>port.claim({nodeId:'worker-a',principal:principals[0]}),{code:'CLAIM_ALREADY_DELIVERED'});await assert.rejects(()=>port.report({nodeId:'worker-a',taskId:claim.task.id,principal:{...principals[0],instanceId:'forged'},state:'COMPLETED',result:{}}));revoke();await assert.rejects(()=>port.report({nodeId:'worker-a',taskId:claim.task.id,principal:principals[0],state:'RUNNING'}),{code:'WORKER_UNAUTHORIZED'});assert.equal(store.get('tasks',claim.task.id).state,'RUNNING');}));

test('report refuses stale epoch, forged capsule, wrong bytes and missing trusted close proof',()=>fixture(async({module,port,principals,dispatch,closed,store})=>{await dispatch(0);const claimed=await port.claim({nodeId:'worker-a',principal:principals[0]});const execute=module.createRemoteCpuExecutor({port,principal:principals[0],onClosed:async receipt=>closed.set(receipt.attemptId,receipt)});const result=await execute(claimed.task,{signal:new AbortController().signal});const args={nodeId:'worker-a',principal:principals[0],taskId:claimed.task.id,state:'COMPLETED',result};for(const altered of [{...result,receipt:{...result.receipt,epoch:result.receipt.epoch+1}},{...result,receipt:{...result.receipt,parentSessionId:'forged'}},{...result,outputBase64:Buffer.from('{}').toString('base64')},{...result,receipt:{...result.receipt,processClosed:false}}])await assert.rejects(()=>port.report({...args,result:altered}));assert.equal(store.get('tasks',claimed.task.id).state,'RUNNING');assert.equal((await port.report(args)).state,'COMPLETED');await assert.rejects(()=>port.report(args));}));
test('stop control requests stop without committing terminal state',()=>fixture(async({port,principals,dispatch,store})=>{await dispatch(0);const claim=await port.claim({nodeId:'worker-a',principal:principals[0]});const result=await port.control({nodeId:'worker-a',principal:principals[0],taskId:claim.task.id});assert.equal(result.stopped,false);assert.equal(result.transport.reason,'NOT_WIRED');assert.equal(store.get('tasks',claim.task.id).state,'RUNNING');}));
test('registration bridge rechecks current worker grant instead of granting an invented membership',()=>fixture(async({module,port,principals,revoke})=>{const request=module.createRemoteWorkerRequest({port,authenticate:async()=>principals[0]});revoke();await assert.rejects(()=>request('node/register',{id:'worker-a'},{}),{code:'WORKER_UNAUTHORIZED'});}));

test('claim nonce survives reconstructed port and dormant port grants no endpoints',()=>fixture(async({module,port,principals,dispatch,reopen})=>{await dispatch(0);await port.claim({nodeId:'worker-a',principal:principals[0]});await assert.rejects(()=>reopen().claim({nodeId:'worker-a',principal:principals[0]}),{code:'CLAIM_ALREADY_DELIVERED'});const dormant=module.createRemoteWorkerPort({enabled:false});assert.deepEqual(dormant.endpoints(),[]);await assert.rejects(()=>dormant.dispatch({}),{code:'REMOTE_NOT_ENABLED'});}));

test('enabled remote port requires a synchronous current authority boundary',()=>fixture(async({module,options})=>{assert.throws(()=>module.createRemoteWorkerPort({...options,validateAuthorityBoundary:undefined}),{code:'REMOTE_CONFIGURATION'});const port=module.createRemoteWorkerPort({...options,validateAuthorityBoundary:async()=>true});await assert.rejects(()=>port.workerStatus({nodeId:'worker-a',principal:{deviceId:'worker-a',bootId:'boot-worker-a',instanceId:'instance-worker-a'}}),{code:'AUTHORITY_BOUNDARY'});}));
test('claim refuses owner revocation during awaited worker recheck before durable nonce',()=>fixture(async({options,dispatch,reopen,principals,revokeOwner,store})=>{await dispatch(0);const check=options.authorizeWorker;let calls=0;options.authorizeWorker=async p=>{const grant=await check(p);if(++calls===2)revokeOwner();return grant;};await assert.rejects(()=>reopen().claim({nodeId:'worker-a',principal:principals[0]}),{code:'AUTHORITY_BOUNDARY'});assert.equal(store.get('tasks','task-0').pcfRemote.claimNonce,null);}));
test('dispatch refuses worker revocation during final awaited owner policy read',()=>fixture(async({options,reopen,principals,revoke,store,dispatch})=>{const original=options.readAuthority;let calls=0;options.readAuthority=async context=>{const facts=await original(context);if(++calls===2)revoke();return facts;};await assert.rejects(()=>dispatch(0),{code:'AUTHORITY_BOUNDARY'});assert.equal(store.get('tasks','task-0').state,'QUEUED');}));

test('report refuses grant revocation during final awaited owner read without canonical completion',()=>fixture(async({module,port,options,reopen,principals,dispatch,closed,revoke,store})=>{await dispatch(0);const claimed=await port.claim({nodeId:'worker-a',principal:principals[0]});const result=await module.createRemoteCpuExecutor({port,principal:principals[0],onClosed:async receipt=>closed.set(receipt.attemptId,receipt)})(claimed.task,{signal:new AbortController().signal});const original=options.readAuthority;let calls=0;options.readAuthority=async context=>{const facts=await original(context);if(++calls===2)revoke();return facts;};await assert.rejects(()=>reopen().report({nodeId:'worker-a',principal:principals[0],taskId:claimed.task.id,state:'COMPLETED',result}),{code:'AUTHORITY_BOUNDARY'});assert.equal(store.get('tasks',claimed.task.id).state,'RUNNING');}));
test('input delivery refuses owner revocation during awaited artifact read',()=>fixture(async({port,options,reopen,principals,dispatch,revokeOwner})=>{await dispatch(0);const claim=await port.claim({nodeId:'worker-a',principal:principals[0]});const original=options.artifacts.read;options.artifacts.read=async(...args)=>{const bytes=await original(...args);revokeOwner();return bytes;};await assert.rejects(()=>reopen().input({nodeId:'worker-a',principal:principals[0],taskId:claim.task.id,claimNonce:claim.task.pcfRemote.claimNonce}),{code:'AUTHORITY_BOUNDARY'});}));
