import test from 'node:test';
import {execFileSync} from 'node:child_process';
const actualSha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {freezeResearchStudy,runLocalStudy,comparePolicies,readSourceIdentity} from '../services/personal-compute-fabric/research-study.mjs';
const config=()=>({version:1,id:'local-study',repetitions:2,stopAfterMs:60000,softwareSha:actualSha,workloads:['cpu-sort','cpu-sum'],hypotheses:['Local CPU produces canonical results'],evidenceClass:'ACTUAL_LOCAL_CPU',inputs:{'cpu-sort':{values:[3,1,2]},'cpu-sum':{values:[3,1,2]}},controls:{hardware:'host-local',cache:'UNCONTROLLED',network:'NO_REMOTE_EXECUTION'},analysis:'DESCRIPTIVE_ONLY',failureCounting:'KEEP_ALL'});
test('configuration is detached, deeply frozen and refuses simulated actual labels',()=>{const c=config(),f=freezeResearchStudy(c);c.inputs['cpu-sort'].values[0]=9;assert.equal(f.inputs['cpu-sort'].values[0],3);assert.ok(Object.isFrozen(f.inputs));assert.throws(()=>freezeResearchStudy({...config(),evidenceClass:'SIMULATED'}));assert.throws(()=>freezeResearchStudy({...config(),failureCounting:'DROP_FAILURES'}));});
test('two actual local CPU workloads retain repetitions, canonical task/action, trace replay and digests',async()=>{const dir=await mkdtemp(join(tmpdir(),'pcf721-'));try{const observedSource=await readSourceIdentity();const r=await runLocalStudy(config(),{directory:dir,allowDirtySnapshot:true,deviceId:'alien'});assert.equal(r.trials.length,4);assert.ok(r.trials.every(t=>t.state==='COMPLETED'&&t.taskRef&&t.actionRef&&t.processId>0));assert.deepEqual(r.trials[0].output.values,[1,2,3]);assert.equal(r.trials[1].output.sum,6);assert.equal(r.trace.replayValidated,true);assert.equal(r.physicalAcceptance,'NOT_RUN');
// PCF-721 line 49: clock-skew handling is reproducible from the pack. Durations come from the monotonic clock, and the
// one thing this host cannot measure - the skew BETWEEN hosts - is recorded as NOT_MEASURED with what it would take.
assert.equal(r.clocks.durationSource,'PROCESS_HRTIME_MONOTONIC');assert.equal(r.clocks.crossHostSkew.status,'NOT_MEASURED');assert.equal(r.clocks.crossHostSkew.reason,'SINGLE_HOST_HAS_NO_INDEPENDENT_REFERENCE');assert.match(r.clocks.durationHandling,/monotonic differences/);assert.ok(r.trials.every(t=>Number.isFinite(t.durationMs)&&t.durationMs>=0),'per-trial durations are measured, not inferred from wall-clock subtraction');assert.equal(r.summary.completed,4);assert.equal(r.sourceIdentity.head,actualSha);assert.equal(r.sourceIdentity.clean,observedSource.clean);assert.equal(r.sourceIdentity.state,observedSource.clean?'CLEAN_EXACT_SHA':'DIRTY_COMPONENT_SNAPSHOT');assert.equal(r.sourceIdentity.frozenSource,observedSource.clean);if(!observedSource.clean)assert.ok(r.sourceIdentity.dirtyFiles.length>0);}finally{await rm(dir,{recursive:true,force:true});}});
test('authority refusals retained and never presented as completed CPU execution',async()=>{const dir=await mkdtemp(join(tmpdir(),'pcf721-denied-'));try{const r=await runLocalStudy({...config(),repetitions:1},{directory:dir,allowDirtySnapshot:true,deviceId:'alien',readAuthority:async()=>({authorized:false})});assert.equal(r.trials.length,2);assert.ok(r.trials.every(t=>t.state==='FAILED'&&t.processId===null&&t.error));assert.equal(r.summary.failed,2);}finally{await rm(dir,{recursive:true,force:true});}});
test('counterfactual strategies reuse safety shield and never dispatch',()=>{const r=comparePolicies({workload:{dataScope:'PUBLIC'},candidates:[],policy:{},now:1});assert.equal(r.evidenceClass,'COUNTERFACTUAL_SIMULATION');assert.ok(r.conditions.every(c=>c.dispatchAllowed===false&&c.result.state==='REFUSED'));});
test('stopping rule preserves every remaining planned trial as NOT_RUN',async()=>{const dir=await mkdtemp(join(tmpdir(),'pcf721-stop-'));try{const r=await runLocalStudy({...config(),stopAfterMs:0.00001},{directory:dir,allowDirtySnapshot:true});assert.equal(r.trials.length,4);assert.equal(r.summary.notRun,4);assert.ok(r.trials.every(t=>t.taskRef===null));}finally{await rm(dir,{recursive:true,force:true});}});
test('trace replay rejects changed persisted normalization rather than asserting successful execution replay',async()=>{const {readFile,writeFile}=await import('node:fs/promises');const {createTraceCollector}=await import('../services/research-trace/index.mjs');const dir=await mkdtemp(join(tmpdir(),'pcf721-tamper-'));try{const r=await runLocalStudy({...config(),repetitions:1},{directory:dir,allowDirtySnapshot:true});const file=join(r.trace.directory,'trace.jsonl');const lines=(await readFile(file,'utf8')).trim().split('\n').map(JSON.parse);lines[0].normalized.type='TAMPERED';await writeFile(file,lines.map(JSON.stringify).join('\n')+'\n');const replay=createTraceCollector({directory:r.trace.directory});await replay.flush();assert.equal(replay.snapshot().storageState,'FAILED');assert.ok(replay.snapshot().failures.some(f=>f.code==='TRACE_REPLAY_MISMATCH'));await replay.close();}finally{await rm(dir,{recursive:true,force:true});}});
test('source mismatch and dirty checkout cannot become frozen provenance',async()=>{const dir=await mkdtemp(join(tmpdir(),'pcf721-source-'));try{const r=await runLocalStudy({...config(),softwareSha:'0'.repeat(40)},{directory:dir,allowDirtySnapshot:true});assert.equal(r.summary.completed,0);assert.ok(r.infrastructureFailures.some(f=>f.code==='STUDY_SOURCE_MISMATCH'));const observedSource=await readSourceIdentity();const production=await runLocalStudy(config(),{directory:dir});assert.equal(production.sourceIdentity.clean,observedSource.clean);if(!observedSource.clean){assert.ok(production.infrastructureFailures.some(f=>f.code==='STUDY_SOURCE_DIRTY'));assert.equal(production.summary.notRun,4);}else{assert.equal(production.sourceIdentity.state,'CLEAN_EXACT_SHA');assert.equal(production.sourceIdentity.frozenSource,true);assert.equal(production.summary.completed,4);assert.ok(!production.infrastructureFailures.some(f=>f.code==='STUDY_SOURCE_DIRTY'));}}finally{await rm(dir,{recursive:true,force:true});}});
test('events infrastructure failure retains completed trial and every remaining planned sample in persisted report',async()=>{const {Store}=await import('../services/dev-gateway/store.mjs');const {readFile}=await import('node:fs/promises');const original=Store.prototype.events;const dir=await mkdtemp(join(tmpdir(),'pcf721-infra-'));try{Store.prototype.events=()=>{throw Object.assign(new Error('events unavailable'),{code:'EVENTS_INJECTED_FAILURE'});};const r=await runLocalStudy(config(),{directory:dir,allowDirtySnapshot:true});assert.equal(r.trials.length,4);assert.equal(r.summary.completed,1);assert.equal(r.summary.notRun,3);assert.ok(r.infrastructureFailures.some(f=>f.code==='EVENTS_INJECTED_FAILURE'));assert.deepEqual(JSON.parse(await readFile(join(dir,r.runId+'-report.json'),'utf8')).trials,r.trials);}finally{Store.prototype.events=original;await rm(dir,{recursive:true,force:true});}});


test('report persistence failure exposes recoverable planned ledger and cannot report success',async()=>{const {writeFile}=await import('node:fs/promises');const dir=await mkdtemp(join(tmpdir(),'pcf721-report-write-'));try{const blocked=join(dir,'file');await writeFile(blocked,'not a directory');await assert.rejects(()=>runLocalStudy(config(),{directory:blocked,allowDirtySnapshot:true}),error=>{assert.equal(error.code,'STUDY_REPORT_WRITE_FAILED');assert.equal(error.report.trials.length,4);assert.equal(error.report.summary.completed,0);assert.ok(error.report.infrastructureFailures.some(f=>f.phase==='REPORT_WRITE'));return true;});}finally{await rm(dir,{recursive:true,force:true});}});
test('staged-only source contents and index changes alter bounded snapshot identity in an isolated repository',async()=>{const {readSourceIdentity}=await import('../services/personal-compute-fabric/research-study.mjs');const {writeFile}=await import('node:fs/promises');const dir=await mkdtemp(join(tmpdir(),'pcf721-staged-'));const git=args=>execFileSync('git',args,{cwd:dir,encoding:'utf8'});try{git(['init','-q']);git(['config','user.name','Component Test']);git(['config','user.email','component@example.invalid']);await writeFile(join(dir,'source.mjs'),'export const value=0;\n');git(['add','source.mjs']);git(['commit','-qm','fixture']);await writeFile(join(dir,'source.mjs'),'export const value=1;\n');git(['add','source.mjs']);const first=await readSourceIdentity({root:dir});assert.ok(first.dirtyFiles.some(f=>f.path==='source.mjs'));await writeFile(join(dir,'source.mjs'),'export const value=2;\n');git(['add','source.mjs']);const second=await readSourceIdentity({root:dir});assert.notEqual(first.indexDiffDigest,second.indexDiffDigest);assert.notEqual(first.snapshotDigest,second.snapshotDigest);assert.notEqual(first.dirtyFiles[0].digest,second.dirtyFiles[0].digest);await writeFile(join(dir,'source.mjs'),'export const value=1;\n');const worktreeBack=await readSourceIdentity({root:dir});git(['add','source.mjs']);const restaged=await readSourceIdentity({root:dir});assert.equal(worktreeBack.dirtyFiles[0].digest,restaged.dirtyFiles[0].digest);assert.notEqual(worktreeBack.indexDiffDigest,restaged.indexDiffDigest);}finally{await rm(dir,{recursive:true,force:true});}});
