import test from 'node:test';import assert from 'node:assert/strict';import {parseNvidiaDeviceObservation,observeNvidia,acceleratorConstraint,createNvidiaResourceAdapter} from '../services/personal-compute-fabric/resource-adapters.mjs';import {createAdapterRegistry} from '../services/personal-compute-fabric/adapters.mjs';import {observeResources} from '../contracts/personal-compute-fabric-v1/observations.mjs';
const line='GPU-abc, 555.85, RTX, 8192 MiB, 7000 MiB, 8 %, 49, 8.70 W';const config={deviceId:'GPU-abc',driverVersion:'555.85',requiredVRAMBytes:1000,canonicalReservedBytes:2000,maximumTemperatureCelsius:70,maximumPowerWatts:100};
test('720 stable driver/device identity, explicit units and safe integer bounds reject overflow and ambiguous source',()=>{const o=parseNvidiaDeviceObservation(line,100);assert.equal(o.deviceId,'GPU-abc');assert.equal(o.utilizationRatio,.08);assert.equal(o.energyJoules,null);assert.equal(o.runtimeVersion,null);for(const altered of [line.replace('7000 MiB','9000 MiB'),line.replace('8 %','101 %'),line.replace('8192 MiB','9'.repeat(400)+' MiB'),line.replace('555.85','unknown')])assert.equal(parseNvidiaDeviceObservation(altered,100).state,'UNKNOWN');});
test('720 current canonical reservations and explicit safety constraints refuse stale/driver-change/hot/unknown measurements',()=>{const o=parseNvidiaDeviceObservation(line,100);assert.equal(acceleratorConstraint(o,config,101).eligible,true);for(const c of [{driverVersion:'new'},{deviceId:'GPU-replaced'},{canonicalReservedBytes:o.memoryFreeBytes},{maximumTemperatureCelsius:40},{maximumPowerWatts:5}])assert.equal(acceleratorConstraint(o,{...config,...c},101).eligible,false);assert.equal(acceleratorConstraint(o,config,5100).reason,'REMEASURE');assert.equal(acceleratorConstraint({...o,temperatureCelsius:null},config,101).reason,'THERMAL_UNKNOWN');});
test('720 optional adapter reuses 701 observations and does not silently aggregate heterogeneous GPUs',async()=>{const adapter=createNvidiaResourceAdapter({sample:async()=>[parseNvidiaDeviceObservation(line,100)]});const sample=await adapter.sample(100);const observation=observeResources(sample.sample,{receivedAt:100});assert.equal(observation.dimensions.vram.presence,'OBSERVED');assert.equal(observation.dimensions.vram.unit,'bytes');const many=createNvidiaResourceAdapter({sample:async()=>[parseNvidiaDeviceObservation(line,100),parseNvidiaDeviceObservation(line,100)]});assert.equal((await many.sample(100)).sample.vram.value,null);});
test('720 absent driver remains UNSUPPORTED rather than invented zero',async()=>{assert.equal((await observeNvidia({executable:'pcf-no-such-nvidia-executable'}))[0].state,'UNSUPPORTED');});

test('720 malformed OBSERVED shape cannot invent available VRAM or survive invalid freshness',()=>{const o=parseNvidiaDeviceObservation(line,100);for(const bad of [{memoryFreeBytes:undefined},{memoryFreeBytes:NaN},{memoryTotalBytes:Infinity},{observedAt:undefined},{validUntil:NaN},{validUntil:99},{memoryFreeBytes:o.memoryTotalBytes+1}]){const result=acceleratorConstraint({...o,...bad},config,101);assert.equal(result.eligible,false);assert.equal(result.availableVRAMBytes,undefined);}});

test('720 real registry retains failed driver reads as UNKNOWN while absent driver remains UNSUPPORTED',async()=>{for(const state of ['UNKNOWN','UNSUPPORTED']){const registry=createAdapterRegistry({adapters:[createNvidiaResourceAdapter({sample:async()=>[{state,reason:'PROBE'}]})],now:()=>100});const collected=await registry.collect();const o=observeResources(collected.sample,{receivedAt:100,unsupported:collected.unsupported});assert.equal(o.dimensions.vram.presence,state);assert.equal(o.dimensions.thermal.presence,state);}});
