import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {Store} from '../services/dev-gateway/store.mjs';import {createCanonicalStateAdapter} from '../services/personal-compute-fabric/canonical-state-adapter.mjs';import {createArtifactStore} from '../services/personal-compute-fabric/artifacts.mjs';
import {normalizeWorkload} from '../services/personal-compute-fabric/workload.mjs';import {resolveEffectivePolicy} from '../services/personal-compute-fabric/policy.mjs';import {planPlacement} from '../services/personal-compute-fabric/placement.mjs';import {admit,claimAttempt,recordOwnedProcess,commitResult} from '../services/personal-compute-fabric/admission.mjs';import {compileExecutionCapsule,validateResultEnvelope} from '../services/personal-compute-fabric/execution-capsule.mjs';import {createEngineeringRuntime} from '../services/personal-compute-fabric/engineering-runtime.mjs';import {createEngineeringTools} from '../services/personal-compute-fabric/engineering-tools.mjs';

test('component fixture: real Store admission capsule subprocess durable receipt and same-caller consume',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'pcf728-canonical-'));const store=new Store(dir);let runtime,run;
 try{
 const owner=createCanonicalStateAdapter(store),now=Date.now(),deviceId='fixture-host',bootId='fixture-boot';
 const artifacts=createArtifactStore({root:join(dir,'artifacts'),maxBytes:1048576,maxItems:16,authorize:({operation,metadata,context})=>operation==='PUBLISH'||metadata.owner===context.caller});
 const policy=resolveEffectivePolicy({},{version:1,authorized:true,expiresAt:now+60000,originDeviceId:deviceId,allowedDevices:[deviceId],dataScopes:['PUBLIC'],sharingConsent:false,cloudConsent:false,budget:0},now);
 const w=normalizeWorkload({version:1,taskId:'T-engineering',actionId:'A-engineering',originDeviceId:deviceId,parentSessionId:'caller',appId:'engineering-fixture',kind:'ENGINEERING_FIXTURE',capabilities:['code.generate'],resources:{cpu:1},dataScope:'PUBLIC',qos:'BATCH',retryClass:'PURE',inputRefs:[],writeScope:[],outputSchema:'json',deadlineAt:now+60000});
 const candidate={deviceId,bootId,trusted:true,authorized:true,sharing:true,executorReady:true,provider:{id:'node-fixture',ready:true,capabilities:['code.generate'],workloadKinds:['ENGINEERING_FIXTURE']},free:{cpu:2},observationVersion:1,observedAt:now,validUntil:now+30000,queueMs:0,cost:{inputMs:[0,1],coldStartMs:[0,2000],executeMs:[0,1000],returnMs:[0,1]}};
 async function access(id,context){const task=store.get('tasks',id);assert.equal(task.parentSessionId,context.sessionId);assert.equal(task.originDeviceId,context.deviceId);return task;}
 const service={
  async submit(spec,context){assert.equal(spec.parentSessionId,context.sessionId);store.put('tasks',{id:w.taskId,state:'QUEUED',actionId:w.actionId,parentSessionId:w.parentSessionId,originDeviceId:deviceId});store.put('actions',{id:w.actionId,taskId:w.taskId});
   const inputRef=await artifacts.publish(Buffer.from('fixture-input'),{owner:context.sessionId,dataScope:'PUBLIC',expiresAt:w.deadlineAt,schema:'text'},now);
   const proposal=planPlacement(w,[candidate],policy,now);const reservation=admit(owner,{workload:w,proposal,policy,candidate,idempotencyKey:'caller:fixture',ttlMs:20000,appQuota:{cpu:2},now}).reservation;
   const attempt=claimAttempt(owner,{reservationId:reservation.id,holder:'fixture-owner',bootId,now});const capsule=compileExecutionCapsule(w,{attemptId:attempt.id,epoch:attempt.epoch,executorDeviceId:deviceId,bootId,providerId:'node-fixture',inputDigest:inputRef.digest,policy},now);
   runtime=createEngineeringRuntime({executable:process.execPath,componentFixture:true,approved:true,hostId:deviceId,bootId,fixtureArgs:['-e','process.stdin.resume();process.stdin.on("end",()=>process.stdout.write(JSON.stringify({type:"thread.started",thread_id:"owned-fixture"})+"\\n"+JSON.stringify({type:"turn.completed",output:{value:6*7}})+"\\n"))'],validateWorkspace:async request=>({baseSha:request.baseSha,workspace:dir}),
    onStart:async(receipt,fence)=>{assert.equal(fence.isCurrent(),true);return recordOwnedProcess(owner,{taskId:w.taskId,attemptId:attempt.id,epoch:attempt.epoch,holder:attempt.holder,bootId,processIdentity:{pid:receipt.pid,host:deviceId,startedAt:Date.now()}});},
    persistReceipt:async(receipt,fence)=>{assert.equal(receipt.ownedStartPersisted,true);assert.equal(fence.isCurrent(),true);const events=await runtime.events({sessionId:receipt.sessionId});const output=events.events.find(e=>e.type==='turn.completed').output;const outputRef=await artifacts.publish(Buffer.from(JSON.stringify(output)),{owner:context.sessionId,dataScope:'PUBLIC',expiresAt:Date.now()+60000,schema:'json'},Date.now());
     const envelope={...capsule,version:1,outcome:receipt.state,exitCode:receipt.exitCode,outputDigest:outputRef.digest,outputRef,runtimeReceipt:receipt,evidenceClass:'COMPONENT_FIXTURE'};validateResultEnvelope(capsule,envelope,{policy,now:Date.now()});assert.equal(fence.isCurrent(),true);commitResult(owner,{...envelope,holder:attempt.holder});},
   });run=await runtime.submit({taskId:w.taskId,attemptId:attempt.id,approved:true,isolatedWorktree:dir,baseSha:'a'.repeat(40),prompt:'fixture'});return {taskId:w.taskId,state:'ACCEPTED',evidenceClass:'COMPONENT_FIXTURE'};
  },
  inspect:access,
  async cancel(id,context){await access(id,context);return runtime.control({sessionId:run.sessionId,operation:'CANCEL'});},
  async collect(id,context){const task=await access(id,context);assert.equal(task.state,'COMPLETED');await runtime.result({sessionId:run.sessionId});const bytes=await artifacts.read(task.pcfResult.outputRef,{caller:context.sessionId},Date.now());return {taskId:id,digest:task.pcfResult.outputDigest,output:JSON.parse(bytes),delivered:true,consumed:task.pcfConsumedSessionId===context.sessionId};},
  async acknowledge(id,context,digest){await access(id,context);return store.atomic(()=>{const task=store.get('tasks',id);assert.equal(task.pcfResult.outputDigest,digest);store.put('tasks',{...task,pcfConsumedSessionId:context.sessionId});return {taskId:id,consumed:true};});},
 };
 const tools=createEngineeringTools(service,{sessionId:'caller',deviceId,authorize:async()=>true});const accepted=await tools.submitRemoteJob({parentSessionId:'caller'});assert.equal(accepted.state,'ACCEPTED');const exit=await runtime.wait(run.sessionId);assert.equal(exit.durableReceipt,true);assert.ok(store.get('tasks',w.taskId).pcfProcessIdentity.pid>0);
 const result=await tools.collectRemoteResult(w.taskId);assert.equal(result.consumed,false);const subsequentInput=result.output.value+1;assert.equal(subsequentInput,43);await tools.acknowledgeRemoteResult(w.taskId,result.digest);assert.equal((await tools.collectRemoteResult(w.taskId)).consumed,true);
 const wrong=createEngineeringTools(service,{sessionId:'other',deviceId,authorize:async()=>true});await assert.rejects(wrong.collectRemoteResult(w.taskId));assert.equal(owner.snapshot().reservations.length,0);
 }finally{store.db.close();await rm(dir,{recursive:true,force:true});}
});
