import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,mkdirSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createFaultController} from '../services/dev-gateway/research/faults.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function fixture(options={}){const dir=mkdtempSync(join(tmpdir(),'rex804-'));const rows=[];const controller=createFaultController({dir,clock:()=>0,node:id=>id==='target'?{id,online:true}:null,trace:{captureCanonical:event=>{rows.push(event);return true;}},...options});return {controller,dir,rows,cleanup:()=>{controller.close();rmSync(dir,{recursive:true,force:true});}};}
const request=kind=>({kind,nodeId:'target',durationMs:50,confirmation:'FAULT:'+kind+':target'});
test('fault confirmation, live canonical target and bounded duration required',()=>{const f=fixture();try{assert.throws(()=>f.controller.start({...request('HEARTBEAT_LOSS'),confirmation:''}),/FAULT_CONFIRMATION_REQUIRED/);assert.throws(()=>f.controller.start({...request('HEARTBEAT_LOSS'),durationMs:30001}),/INVALID_FAULT/);assert.throws(()=>f.controller.start({...request('HEARTBEAT_LOSS'),nodeId:'missing',confirmation:'FAULT:HEARTBEAT_LOSS:missing'}),/FAULT_TARGET_NOT_READY/);assert.equal(f.controller.list().faults.length,0);}finally{f.cleanup();}});
test('heartbeat loss refuses only targeted heartbeats, stop and expiry restore requests',async()=>{let time=0;const f=fixture({clock:()=>time});try{const row=f.controller.start(request('HEARTBEAT_LOSS'));await assert.rejects(()=>f.controller.before('heartbeat','target'),/FAULT_INJECTED_HEARTBEAT_LOSS/);await f.controller.before('heartbeat','other');await f.controller.before('claim','target');f.controller.stop(row.faultId);await f.controller.before('heartbeat','target');assert.equal(f.controller.get(row.faultId).status,'STOPPED');const timed=f.controller.start({...request('HEARTBEAT_LOSS'),durationMs:5});time=6;await sleep(15);await f.controller.before('heartbeat','target');assert.equal(f.controller.get(timed.faultId).status,'EXPIRED');}finally{f.cleanup();}});
test('provider unavailable refuses targeted claim and records measured recovery after stop',async()=>{const f=fixture();try{const row=f.controller.start(request('PROVIDER_UNAVAILABLE'));await assert.rejects(()=>f.controller.before('claim','target'),/FAULT_INJECTED_PROVIDER_UNAVAILABLE/);f.controller.stop(row.faultId);await f.controller.before('claim','target');f.controller.success('claim','target');const out=f.controller.get(row.faultId);assert.equal(out.metrics.injectedFailureCount,1);assert.ok(out.metrics.recoveryTimeMs>=0);assert.equal(out.metrics.detectionTimeMs,null);}finally{f.cleanup();}});
test('delayed report releases immediately on emergency stop without blocking unrelated requests',async()=>{const f=fixture();try{const row=f.controller.start({...request('DELAY_RESULT'),durationMs:500});let done=false;const waiting=f.controller.before('report','target').then(()=>done=true);await f.controller.before('report','other');await sleep(5);assert.equal(done,false);f.controller.stop(row.faultId);await waiting;assert.equal(done,true);}finally{f.cleanup();}});
test('duplicate event affects observation only and is absent after emergency stop',()=>{const f=fixture();try{const row=f.controller.start(request('DUPLICATE_EVENT'));const event={id:'event',actor:'target',type:'TASK_RUNNING',taskId:'task'};f.controller.capture(event);assert.equal(f.rows.length,2);assert.equal(f.rows[0].id,f.rows[1].id);assert.equal(f.controller.get(row.faultId).metrics.duplicateObservationCount,1);f.controller.stop(row.faultId);f.controller.capture(event);assert.equal(f.rows.length,3);}finally{f.cleanup();}});
test('restart disables persisted activation and never resumes fault silently',()=>{const f=fixture();let restarted;try{const row=f.controller.start(request('PROVIDER_UNAVAILABLE'));restarted=createFaultController({dir:f.dir,node:()=>({online:true}),trace:{captureCanonical:()=>true}});assert.equal(restarted.get(row.faultId).status,'INTERRUPTED');assert.doesNotThrow(()=>restarted.capture({actor:'target'}));}finally{restarted?.close();f.cleanup();}});
test('unexercised or stopped fault cannot receive unrelated future detection or recovery measurements',()=>{const f=fixture();try{const row=f.controller.start(request('HEARTBEAT_LOSS'));f.controller.stop(row.faultId);f.controller.observeOffline('target');f.controller.success('heartbeat','target');const out=f.controller.get(row.faultId);assert.equal(out.metrics.detectionTimeMs,null);assert.equal(out.metrics.recoveryTimeMs,null);}finally{f.cleanup();}});
test('expired fault persistence failure cannot turn normal canonical observation into an error',()=>{const f=fixture();let c;try{let time=0;c=createFaultController({dir:join(f.dir,'expiry'),node:()=>({online:true}),clock:()=>time,trace:{captureCanonical:e=>{f.rows.push(e);return true;}}});const row=c.start(request('DUPLICATE_EVENT'));mkdirSync(join(f.dir,'expiry',row.faultId+'.json.tmp'));time=100;assert.doesNotThrow(()=>c.capture({actor:'target',id:'canonical'}));assert.equal(f.rows.length,1);}finally{c?.close();f.cleanup();}});
