import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createGateway} from '../services/dev-gateway/server.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
test('four fault classes change real Gateway boundaries and emergency stop restores canonical requests',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'rex804-http-'));let app=await createGateway({dir,port:0,token:'ctl',nodeToken:'node',roomsDisabled:true,heartbeatTimeout:100});
 const request=(path,body,token='ctl')=>fetch(app.url+'/api/v0/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-City-Api-Version':'0','X-City-Schema-Version':'0'},body:body?JSON.stringify(body):undefined});
 const node=(path,body)=>request('node/'+path,body,'node');const start=async kind=>{const response=await request('research/faults',{kind,nodeId:'target',durationMs:3000,confirmation:'FAULT:'+kind+':target'});assert.equal(response.status,200,await response.clone().text());return (await response.json()).fault;};const stop=row=>request('research/faults/'+row.faultId+'/stop',{});
 try{
  const register=id=>({id,displayName:id,metadata:{platform:'reference'},capabilities:['task.execute.safe','filesystem.temp']});await node('register',register('target'));await node('register',register('other'));
  assert.equal((await request('research/faults',{},'node')).status,401);
  const a=await start('HEARTBEAT_LOSS');assert.equal((await node('heartbeat',{id:'target'})).status,503);assert.equal((await node('heartbeat',{id:'other'})).status,200);await sleep(1100);assert.equal(app.store.get('nodes','target').online,false);await stop(a);assert.equal((await node('heartbeat',{id:'target'})).status,200);const measured=(await (await request('research/faults/'+a.faultId)).json()).fault;assert.ok(measured.metrics.detectionTimeMs>=100);assert.ok(measured.metrics.recoveryTimeMs>=0);
  const b=await start('PROVIDER_UNAVAILABLE');assert.equal((await node('claim',{id:'target'})).status,503);assert.equal((await node('claim',{id:'other'})).status,200);await stop(b);assert.equal((await node('claim',{id:'target'})).status,200);
  const task=await (await request('tasks',{type:'WAIT'})).json();await node('claim',{id:'target'});const c=await start('DELAY_RESULT');let done=false;const delayed=node('report',{id:'target',taskId:task.id,state:'RUNNING',progress:10}).then(r=>{done=true;return r;});await sleep(20);assert.equal(done,false);assert.equal((await request('health')).status,200);await stop(c);assert.equal((await delayed).status,200);
  const d=await start('DUPLICATE_EVENT');await node('report',{id:'target',taskId:task.id,state:'COMPLETED',progress:100,result:{ok:true}});await app.researchTrace.flush();const snapshots=app.researchTrace.snapshot().records.filter(r=>r.canonicalRefs.taskRef===task.id);assert.ok(snapshots.some(r=>r.annotations.includes('DUPLICATE_EVENT')));assert.equal(app.store.events().filter(e=>e.taskId===task.id&&e.type==='TASK_COMPLETED').length,1);await stop(d);
 }finally{await app.close();await rm(dir,{recursive:true,force:true});}
});
