import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createScenarioRunner} from '../services/dev-gateway/research/runner.mjs';
const manifest={experimentId:'runner-study',repetitions:3,seedPolicy:'PER_REPETITION',baseSeed:19,variables:{independent:['target']},hosts:['Alien'],workers:['Alien'],controlSurfaces:['Android'],softwareRefs:['utopia@1a26d7499d3de39b19c3136c3032e8ccd9343428'],stopConditions:[{kind:'MAX_REPETITIONS',value:3}]};
function fixture(mode='complete',extra={}){
 const dir=mkdtempSync(join(tmpdir(),'rex803-'));let next=0;const tasks=new Map();const cancelled=[];
 const adapter={readiness:()=>({ready:true,missing:[]}),create:(_type,options)=>{const id='task-'+(++next);tasks.set(id,{id,state:mode==='complete'?'COMPLETED':'RUNNING',researchRunRef:options?.researchRunRef});return {id};},owned:ref=>[...tasks.values()].filter(t=>t.researchRunRef===ref),get:id=>tasks.get(id),cancel:id=>{cancelled.push(id);tasks.get(id).state='CANCELLED';}};
 const runner=createScenarioRunner({dir,registry:{get:()=>({status:'VALIDATED',manifest:{...manifest,...extra}})},adapter,pollMs:2});
 return {runner,dir,adapter,cancelled,tasks,cleanup:async()=>{await runner.close();rmSync(dir,{recursive:true,force:true});}};
}
async function finished(runner,id){for(let i=0;i<300;i++){const row=runner.get(id);if(row.status!=='RUNNING')return row;await new Promise(r=>setTimeout(r,5));}throw Error('campaign did not terminate');}
const options={scenario:'WAIT',repetitions:3,warmups:1,timeoutMs:40,resumePolicy:'INTERRUPT'};
test('warmups excluded, measured seeds repeat across fresh campaigns, all task receipts retained',async()=>{const f=fixture();try{const a=await finished(f.runner,f.runner.start('runner-study',options).campaignId);const b=await finished(f.runner,f.runner.start('runner-study',options).campaignId);assert.equal(a.status,'COMPLETED');assert.equal(a.runs.length,4);assert.equal(a.runs[0].exclusionReason,'WARMUP');assert.equal(a.summary.successfulRuns,3);assert.deepEqual(a.runs.filter(r=>!r.warmup).map(r=>r.seed),b.runs.filter(r=>!r.warmup).map(r=>r.seed));assert.ok(a.runs.every(r=>r.taskRef&&r.durationMs>=0));}finally{await f.cleanup();}});
test('timeout cancels owned canonical task and preserves excluded failures',async()=>{const f=fixture('pending');try{const a=await finished(f.runner,f.runner.start('runner-study',{...options,warmups:0,repetitions:1,timeoutMs:10}).campaignId);assert.equal(a.runs[0].outcome,'TIMEOUT');assert.equal(a.runs[0].exclusionReason,'RUN_TIMEOUT');assert.equal(f.cancelled.length,1);}finally{await f.cleanup();}});
test('stop cancels current task, launches no next run and keeps partial receipt',async()=>{const f=fixture('pending');try{const a=f.runner.start('runner-study',options);await new Promise(r=>setTimeout(r,5));f.runner.stop(a.campaignId);const end=await finished(f.runner,a.campaignId);assert.equal(end.status,'CANCELLED');assert.equal(end.runs.length,1);assert.equal(f.cancelled.length,1);assert.equal(end.runs[0].outcome,'CANCELLED');}finally{await f.cleanup();}});
test('restart interrupts campaign, cancels pending work, never silently resumes',async()=>{const f=fixture('pending');let restarted;try{const a=f.runner.start('runner-study',options);await new Promise(r=>setTimeout(r,5));restarted=createScenarioRunner({dir:f.dir,registry:{get:()=>({status:'VALIDATED',manifest})},adapter:f.adapter});const row=restarted.get(a.campaignId);assert.equal(row.status,'INTERRUPTED');assert.equal(row.runs[0].exclusionReason,'PROCESS_RESTART');assert.equal(f.tasks.size,1);assert.equal(f.tasks.values().next().value.state,'CANCELLED');}finally{await restarted?.close();await f.cleanup();}});
test('topology refusal and configuration bounds prevent canonical task creation',async()=>{const f=fixture();try{const runner=createScenarioRunner({dir:join(f.dir,'refusal'),registry:{get:()=>({status:'VALIDATED',manifest})},adapter:{...f.adapter,readiness:()=>({ready:false,missing:['Android']})}});assert.throws(()=>runner.start('runner-study',options),/TOPOLOGY_NOT_READY/);assert.throws(()=>f.runner.start('runner-study',{...options,repetitions:1001}),/INVALID_CAMPAIGN/);assert.throws(()=>f.runner.start('runner-study',{...options,resumePolicy:'AUTO'}),/INVALID_CAMPAIGN/);assert.equal(f.tasks.size,0);await runner.close();}finally{await f.cleanup();}});
test('MAX_FAILURES stops measured repetition while retaining failed receipt',async()=>{const f=fixture('pending',{stopConditions:[{kind:'MAX_REPETITIONS',value:3},{kind:'MAX_FAILURES',value:1}]});try{const a=await finished(f.runner,f.runner.start('runner-study',{...options,warmups:0,timeoutMs:5}).campaignId);assert.equal(a.runs.length,1);assert.equal(a.stopReason,'MAX_FAILURES');assert.equal(a.summary.failedRuns,1);}finally{await f.cleanup();}});
test('completion first observed after deadline remains timeout rather than false success',async()=>{const f=fixture();let runner;try{let time=0;runner=createScenarioRunner({dir:join(f.dir,'deadline'),clock:()=>time,registry:{get:()=>({status:'VALIDATED',manifest})},adapter:{...f.adapter,get:id=>{time=20;return f.adapter.get(id);}}});const row=await finished(runner,runner.start('runner-study',{...options,warmups:0,repetitions:1,timeoutMs:10}).campaignId);assert.equal(row.runs[0].outcome,'TIMEOUT');}finally{await runner?.close();await f.cleanup();}});
test('restart discovers canonical ownership when task persisted before campaign taskRef write',async()=>{const f=fixture('pending');let restarted;try{const a=f.runner.start('runner-study',{...options,timeoutMs:1000});await new Promise(r=>setTimeout(r,5));const path=join(f.dir,a.campaignId+'.json');const disk=JSON.parse(readFileSync(path));disk.runs[0].taskRef=null;writeFileSync(path,JSON.stringify(disk));restarted=createScenarioRunner({dir:f.dir,registry:{get:()=>({status:'VALIDATED',manifest})},adapter:f.adapter});assert.equal(restarted.get(a.campaignId).status,'INTERRUPTED');assert.equal(f.tasks.values().next().value.state,'CANCELLED');assert.ok(restarted.get(a.campaignId).runs[0].taskRef);}finally{await restarted?.close();await f.cleanup();}});
