import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,rm,readFile,writeFile}from'node:fs/promises';import{resolve}from'node:path';import{createTraceCollector,normalizeTraceRecord,canonicalEventRecord}from'../services/research-trace/index.mjs';
import {createFileStorage} from '../services/research-trace/storage.mjs';
const wall=1700000000000;const raw=(id,seq,extra={})=>({eventId:id,type:'TASK_STARTED',timestamp:new Date(wall).toISOString(),sourceSeq:seq,sourceClock:'CANONICAL_EVENT_WALL_UTC',canonicalRefs:{taskRef:'Q-fixture'},...extra});const ctx={runId:'trace-fixture',capturedAt:new Date(wall).toISOString(),monotonicNs:'1000',collectorEpoch:'epoch-fixture',previousSourceSeq:null,previousSourceAt:null,duplicate:false,softwareRefs:{}};
test('REX802 external resource clocks cannot change canonical sequence time ordering',async()=>{const collector=createTraceCollector({clock:()=>wall,storage:{load:async()=>[],append:async()=>{}}});try{await collector.flush();collector.record(raw('canonical-1',1));collector.record(raw('resource-future',null,{type:'RESOURCE_OBSERVATION',timestamp:new Date(wall+120000).toISOString(),sourceClock:'EXTERNAL_DECLARED_WALL_UTC'}));collector.record(raw('canonical-2',2));await collector.flush();assert.ok(!collector.snapshot().records.at(-1).annotations.includes('SOURCE_TIMESTAMP_REGRESSED'));}finally{await collector.close();}});
test('REX802 broken observation clock remains a contained failure',async()=>{const collector=createTraceCollector({clock:()=>{throw new Error('PRIVATE_CLOCK');},storage:{load:async()=>[],append:async()=>{}}});await collector.flush();assert.doesNotThrow(()=>collector.record(raw('clock',1)));assert.equal(collector.snapshot().failures[0].capturedAt,null);assert.equal(await collector.close(),true);});
test('REX802 rejects an oversized existing file before rotating or modifying it',async()=>{const dir=await mkdtemp(resolve('.scratch-rex802-'));try{const path=resolve(dir,'trace.jsonl');await writeFile(path,'x'.repeat(2048));const storage=createFileStorage(dir,1024);await assert.rejects(storage.append('{}\n'),{code:'TRACE_STORAGE_OVERSIZE'});assert.equal((await readFile(path)).length,2048);}finally{await rm(dir,{recursive:true,force:true});}});
test('REX802 rotation remains explicit after restart and restores bounded previous records',async()=>{const dir=await mkdtemp(resolve('.scratch-rex802-'));let first,second;try{first=createTraceCollector({directory:dir,clock:()=>wall,byteLimit:4096,recordLimit:64});await first.flush();for(let i=1;i<=8;i++){first.record(raw('event-'+i,i));await first.flush();}assert.equal(first.snapshot().retentionTruncated,true);await first.close();first=null;second=createTraceCollector({directory:dir,clock:()=>wall,byteLimit:4096,recordLimit:64});await second.flush();assert.equal(second.snapshot().retentionTruncated,true);assert.equal(second.snapshot().completeness,'PARTIAL');assert.ok(second.snapshot().records.length>=2);assert.ok(second.snapshot().records.length<8);}finally{await first?.close();await second?.close();await rm(dir,{recursive:true,force:true});}});
test('REX802 pure normalization binds clocks/provenance and retains unknown metrics',()=>{const n=normalizeTraceRecord(raw('event-1',1),ctx);assert.equal(n.runId,'trace-fixture');assert.equal(n.metrics.cpuPercent.value,null);assert.ok(n.metrics.cpuPercent.reason);assert.equal(n.provenance.softwareSha,null);assert.ok(n.missingFields.includes('softwareSha'));assert.equal(n.clocks.source,'CANONICAL_EVENT_WALL_UTC');assert.deepEqual(normalizeTraceRecord(raw('event-1',1),ctx),n);assert.throws(()=>normalizeTraceRecord(raw('bad',1,{metrics:{cpuPercent:NaN}}),ctx));});
test('REX802 canonical tap drops arbitrary payload and credentials; explicit measured zero remains zero',()=>{const record=canonicalEventRecord({id:'event-1',seq:1,type:'NODE_ONLINE',timestamp:new Date(wall).toISOString(),payload:{nodeId:'dev-fixture',token:'DO_NOT_LOG',fingerprint:'PRIVATE_FINGERPRINT',input:{secret:'PRIVATE_INPUT'}}});assert.ok(!JSON.stringify(record).includes('DO_NOT_LOG'));assert.ok(!JSON.stringify(record).includes('PRIVATE'));const n=normalizeTraceRecord({...record,metrics:{cpuPercent:0}},ctx);assert.equal(n.metrics.cpuPercent.value,0);assert.equal(n.metrics.cpuPercent.reason,null);});
test('REX802 recognizes missing, duplicate, reordered and stale timestamp observations',()=>{assert.ok(normalizeTraceRecord(raw('a',4),{...ctx,previousSourceSeq:1}).annotations.includes('SOURCE_SEQUENCE_GAP'));assert.ok(normalizeTraceRecord(raw('a',1),{...ctx,duplicate:true,previousSourceSeq:1}).annotations.includes('DUPLICATE_EVENT'));assert.ok(normalizeTraceRecord(raw('a',1),{...ctx,previousSourceSeq:4}).annotations.includes('OUT_OF_ORDER_EVENT'));assert.ok(normalizeTraceRecord(raw('a',1,{timestamp:new Date(wall-600000).toISOString()}),ctx).annotations.includes('STALE_SOURCE_TIMESTAMP'));});
test('REX802 storage raw-to-normalized replay is reproducible and restart starts new epoch',async()=>{const dir=await mkdtemp(resolve('.scratch-rex802-'));let first,second;try{first=createTraceCollector({directory:dir,clock:()=>wall});await first.flush();first.record(raw('event-1',1));assert.equal(await first.flush(),true);const line=JSON.parse((await readFile(resolve(dir,'trace.jsonl'),'utf8')).trim());assert.deepEqual(normalizeTraceRecord(line.raw,line.context),line.normalized);const before=first.snapshot();await first.close();first=null;second=createTraceCollector({directory:dir,clock:()=>wall+1000});assert.equal(await second.flush(),true);assert.equal(second.snapshot().records.length,1);assert.notEqual(second.snapshot().runId,before.runId);second.record(raw('event-2',2));await second.flush();assert.equal(second.snapshot().records.length,2);}finally{await first?.close();await second?.close();await rm(dir,{recursive:true,force:true});}});
test('REX802 collector failures and queue bounds are explicit without throwing into callers',async()=>{const dir=await mkdtemp(resolve('.scratch-rex802-'));let collector;try{collector=createTraceCollector({directory:dir,clock:()=>wall,storage:{load:async()=>[],append:async()=>{throw Object.assign(new Error('sensitive-path-secret'),{code:'EIO'});}},recordLimit:2,queueLimit:2});await collector.flush();assert.doesNotThrow(()=>collector.record(raw('event-1',1)));await collector.flush();assert.equal(collector.snapshot().storageState,'FAILED');assert.ok(!JSON.stringify(collector.snapshot()).includes('sensitive-path-secret'));assert.doesNotThrow(()=>collector.record({bad:'token'}));assert.ok(collector.snapshot().failures.length);}finally{await collector?.close();await rm(dir,{recursive:true,force:true});}});
test('REX802 hung storage is bounded; queue drop and close do not block indefinitely',async()=>{const dir=await mkdtemp(resolve('.scratch-rex802-'));let collector;try{collector=createTraceCollector({directory:dir,clock:()=>wall,storage:{load:async()=>[],append:()=>new Promise(()=>{})},recordLimit:2,queueLimit:2});await collector.flush();for(let i=1;i<=8;i++)collector.record(raw('event-'+i,i));assert.equal(await collector.flush(20),false);const snapshot=collector.snapshot();assert.ok(snapshot.droppedRecords>0);assert.ok(snapshot.records.length<=2);assert.equal(snapshot.completeness,'PARTIAL');await collector.close(20);}finally{await rm(dir,{recursive:true,force:true});}});

test('REX802 early capture waits for restored watermark before normalization',async()=>{const dir=await mkdtemp(resolve('.scratch-rex802-'));let first,second;try{first=createTraceCollector({directory:dir,clock:()=>wall});await first.flush();first.record(raw('event-1',1));await first.close();first=null;second=createTraceCollector({directory:dir,clock:()=>wall});second.record(raw('event-3',3));await second.flush();const records=second.snapshot().records;assert.deepEqual(records.map(r=>r.eventId),['event-1','event-3']);assert.ok(records[1].annotations.includes('SOURCE_SEQUENCE_GAP'));}finally{await first?.close();await second?.close();await rm(dir,{recursive:true,force:true});}});

test('REX802 supports rule lifecycle, supervision quality and semantic integration without invented defaults',()=>{const sha='0e9bea3ce739b979e582a428af8fb233045a5e75';const n=normalizeTraceRecord(raw('governance',1,{dimensions:{ruleLifecycle:{ruleRef:'14C',ruleVersionSha:sha,sourceFailureRef:null,activationCount:null,falseBlockObserved:null},supervision:{category:'RECOVERY_REQUIRED',batchable:null,avoidable:null,priorDiagnosisRef:'mission-book/reports/fixture',resumedAt:null},semanticIntegration:{acceptedSourceShas:[sha],integrationSha:sha,invariantRef:'STRICT_TARGET',driftType:'TEXTUALLY_CLEAN_SEMANTIC_CONFLICT'}}}),ctx);assert.equal(n.dimensions.ruleLifecycle.activationCount,null);assert.equal(n.dimensions.supervision.avoidable,null);assert.deepEqual(n.dimensions.semanticIntegration.acceptedSourceShas,[sha]);assert.throws(()=>normalizeTraceRecord(raw('bad',1,{dimensions:{semanticIntegration:{integrationSha:'main'}}}),ctx));});
