import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';

const api = await import('../index.mjs').catch(() => ({}));
async function fixture(t) {
  const base = await mkdtemp(join(tmpdir(), 'chk-'));
  t.after(() => rm(base, { recursive: true, force: true }));
  const utopia = join(base, 'utopia'), city = join(base, 'city');
  async function put(root, path, value) { await mkdir(join(root, path, '..'), { recursive: true }); await writeFile(join(root, path), typeof value === 'string' ? value : JSON.stringify(value)); }
  await put(utopia, 'services/demo.mjs', 'export function demo() {}\n');
  await put(city, 'capability-registry/records/CAP-DEMO-001.yaml', { schema_version: 1, capability_id: 'CAP-DEMO-001', ownership: { city_owner: 'Engineering', canonical_module: 'services/demo.mjs' }, implementation: { paths: ['services/demo.mjs'], symbols: ['demo'], last_verified_full_sha: null }, status: { implementation_status: 'COMPLETE', backend_wiring_status: 'NOT_TESTED', user_reachability_status: 'MISSING', intent_validation_status: 'NOT_TESTED' }, exposure: { class: 'INTERNAL_ONLY', internal_only_exemption_reason: 'bounded internal seam' }, evidence: {} });
  await put(city, 'mission-book/mission-group/example/WB.md', '---\nworkbook_id: CHK-101\nstatus: IN_DEVELOPMENT\nexecution_enabled: true\ndevelopment_complete: false\nreview_complete: false\n---\n');
  await put(city, 'mission-book/MISSION_PROGRESS.json', { programmes: [{ tasks: [{ id: 'CHK-101', status: 'IN_DEVELOPMENT', execution_enabled: true, development_complete: false, review_complete: false }] }] });
  for (const root of [utopia, city]) { execFileSync('git', ['init', '-q'], { cwd: root }); execFileSync('git', ['add', '.'], { cwd: root }); execFileSync('git', ['-c', 'user.name=CHK', '-c', 'user.email=chk@example.invalid', 'commit', '-qm', 'fixture'], { cwd: root }); }
  return { base, utopia, city, put };
}
const options = f => ({ utopiaRoot: f.utopia, cityRoot: f.city, mode: 'full', maxFiles: 100, maxBytes: 1000000, maxDurationMs: 10000 });
test('CHK990-01 small check obeys a hard file budget and discloses partial coverage', async t => { const f = await fixture(t); const r = await api.runHealthCheck({ ...options(f), mode: 'small', maxFiles: 1 }); assert.equal(r.coverage.complete, false); assert.ok(r.metrics.filesRead <= 1); assert.notEqual(r.outcome, 'HEALTHY'); });
test('CHK990-02 full census reverse-discovers an unregistered API and a dependency cycle', async t => { const f = await fixture(t); await f.put(f.utopia, 'services/new.mjs', "import './loop.mjs';\nexport function orphanAction() {}\nconst route = '/api/v0/unregistered';"); await f.put(f.utopia, 'services/loop.mjs', "import './new.mjs';"); execFileSync('git', ['add', '.'], { cwd: f.utopia }); const r = await api.runHealthCheck(options(f)); assert.ok(r.findings.some(x => x.code === 'UNREGISTERED_CAPABILITY')); assert.ok(r.findings.some(x => x.code === 'DEPENDENCY_CYCLE')); assert.ok(r.census.source.some(x => x.path === 'services/new.mjs')); });
test('CHK990-03 health report never modifies repository state or grants repair authority', async t => { const f = await fixture(t); const before = execFileSync('git', ['status', '--porcelain'], { cwd: f.city }).toString(); const r = await api.runHealthCheck(options(f)); assert.equal(execFileSync('git', ['status', '--porcelain'], { cwd: f.city }).toString(), before); assert.equal(r.authority.execute, false); assert.equal(r.authority.repair, false); for (const x of r.findings) for (const key of ['owner_surface', 'severity', 'evidence', 'recommended_destination']) assert.ok(x[key]); });
test('CHK990-04 suspended workbook cannot become active truth', async t => { const f = await fixture(t); await f.put(f.city, 'mission-book/mission-group/example/WB.md', '---\nworkbook_id: CHK-101\nstatus: PARKED\nexecution_enabled: false\ndevelopment_complete: false\nreview_complete: false\n---\n'); const r = await api.runHealthCheck(options(f)); assert.equal(r.census.activeWorkbooks.length, 0); assert.ok(r.findings.some(x => x.code === 'PARKED_ACTIVE_TRUTH')); });
test('CHK990-05 self model returns unknown runtime and not measured blast radius', async t => { const f = await fixture(t); const r = await api.runHealthCheck(options(f)); const model = api.querySelfModel(r, 'CAP-DEMO-001'); assert.equal(model.runtime_state, 'UNKNOWN'); assert.equal(model.blast_radius, 'NOT_MEASURED'); assert.equal(api.querySelfModel(r, 'missing').state, 'UNKNOWN'); });
test('CHK990-06 diagnosis preserves multiple hypotheses and missing evidence', () => { const d = api.diagnose({ code: 'REGISTRY_RUNTIME_MISMATCH', evidence: [{ path: 'snapshot.json' }] }); assert.ok(d.hypotheses.length >= 2); assert.ok(d.missing_evidence.length); assert.equal(d.root_cause, 'UNVERIFIED'); assert.equal(d.authority.repair, false); });
test('CHK990-07 case revisions retain original hypothesis and detect tampering', () => { const original = api.appendCaseRevision([], { case_id: 'CASE-1', symptom: 'drift', hypotheses: ['initial'], evidence: [{ path: 'first.json' }] }); const revised = api.appendCaseRevision(original, { case_id: 'CASE-1', symptom: 'drift', hypotheses: ['revised'], evidence: [{ path: 'second.json' }] }); assert.equal(revised[0].hypotheses[0], 'initial'); assert.equal(revised[1].previous_hash, revised[0].hash); assert.equal(original.length, 1); const forged = structuredClone(revised); forged[0].hypotheses = ['rewrite']; assert.throws(() => api.appendCaseRevision(forged, { case_id: 'CASE-1' }), /integrity/i); });
test('CHK990-08 all six BLG gaps can retain reference or supersede without migration', () => { const r = api.reconcileBoss({ 'BLG-001': { disposition: 'SUPERSEDED', evidence: [{ path: 'verified.json' }], rationale: 'different bounded implementation' } }); assert.equal(r.length, 6); assert.equal(r[0].disposition, 'SUPERSEDED'); assert.equal(r[5].disposition, 'KEEP_AS_REFERENCE'); assert.ok(r.every(x => x.migration_authority === false)); });
test('CHK990-09 candidate routing never gains execution authority from verified episodes', () => { const r = api.routeCandidate({ candidate_id: 'EV-1', kind: 'research', evidence: [{ path: 'verified.json' }], execution_authority: true }); assert.equal(r.destination, 'REX'); assert.equal(r.execution_authority, false); assert.equal(r.owner_state, 'NOT_OBSERVED'); assert.equal(r.receipt_state, 'ROUTED'); });
test('CHK990-10 routes every supported domain and defers unknown owner', () => { for (const [kind, destination] of Object.entries({ research: 'REX', rule: 'RIV', governance: 'DGX', architecture: 'URA', capability: 'CAPABILITY_LINKED_MISSION', provider: 'GAI_ENGINEERING', boss: 'BOSS_LEGACY_DIFF' })) assert.equal(api.routeCandidate({ candidate_id: kind, kind, evidence: [{ path: 'e.json' }] }).destination, destination); const unknown = api.routeCandidate({ candidate_id: 'unknown', kind: 'unknown', evidence: [] }); assert.equal(unknown.receipt_state, 'DEFERRED'); assert.ok(unknown.defer_reason); });
test('CHK990-11 promotion and rollback require explicit external authority and full safety ladder', () => { const r = api.routeCandidate({ candidate_id: 'EV-2', kind: 'provider', evidence: [{ path: 'episode.json' }] }); assert.equal(r.promotion_authority, 'EXPLICIT_EXTERNAL_OWNER_REQUIRED'); assert.equal(r.rollback_authority, 'DESTINATION_OWNER_REQUIRED'); assert.ok(r.safety_ladder.includes('independent_verification')); assert.ok(r.safety_ladder.includes('shadow')); assert.equal(r.execute, undefined); });
test('CHK990-12 overhead is measurable and runtime seam remains offline and redacted', async t => { const f = await fixture(t); const runtime = { captured_at: '2026-10-07T00:00:00Z', implementation_sha: execFileSync('git', ['rev-parse', 'HEAD'], { cwd: f.utopia }).toString().trim(), capabilities: [{ capability_id: 'CAP-DEMO-001', state: 'OFFLINE', token: 'must-never-appear' }], token: 'must-never-appear' }; const r = await api.runHealthCheck({ ...options(f), runtimeSnapshot: runtime }); assert.equal(api.querySelfModel(r, 'CAP-DEMO-001').runtime_state, 'OFFLINE'); assert.ok(r.metrics.elapsed_ms >= 0); assert.ok(r.metrics.bytesRead > 0); assert.equal(JSON.stringify(r).includes('must-never-appear'), false); assert.equal(r.scheduler_created, false); });
