package city.utopia.control
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test
class MonitorProjectionTest {
 private fun graph()=JSONObject("""{"graph":{"schemaVersion":1,"authoritative":false,"projectionOf":{"cityId":"city-a","health":"PARTIAL"},"nodes":[{"id":"failed","kind":"TASK","state":"FAILED","riskReasons":[{"level":"ACTIVE","code":"TASK_FAILED","evidenceRef":"e1"}]},{"id":"quiet","kind":"TASK","state":"QUEUED","clusterRef":"c1","riskReasons":[]}],"visibleNodeIds":["failed"],"clusters":[{"id":"c1","nodeIds":["quiet"],"count":1}],"edges":[],"events":[{"canonicalEventId":"e1","type":"TASK_FAILED","taskRef":"failed"}],"evidence":[{"canonicalEventId":"e1","source":"CANONICAL_GATEWAY_STORE"}],"summary":{"unobserved":{"tasks":null}}}}""")
 private fun refuses(fn:()->Unit){try{fn();fail("input must be refused")}catch(_:IllegalArgumentException){}}
 @Test fun collapseKeepsRiskAndExpandsOnlySelectedCluster(){val v=parseMonitorGraph(graph(),"city-a");assertEquals(listOf("failed"),v.visibleNodes().map{it.getString("id")});assertEquals(listOf("failed","quiet"),v.visibleNodes(setOf("c1")).map{it.getString("id")})}
 @Test fun exactEvidenceAndMissingEvidenceAreDistinct(){val v=parseMonitorGraph(graph(),"city-a");assertEquals("TASK_FAILED",v.evidence("e1").getJSONObject("event").getString("type"));assertEquals("CANONICAL_GATEWAY_STORE",v.evidence("e1").getJSONObject("pointer").getString("source"));assertEquals("NOT_OBSERVABLE",v.evidence("absent").getString("state"))}
 @Test fun missingHealthAndPopulationStayUnknown(){val r=graph();r.getJSONObject("graph").getJSONObject("projectionOf").remove("health");val v=parseMonitorGraph(r,"city-a");assertEquals("UNKNOWN",v.health);assertTrue(v.raw.getJSONObject("summary").getJSONObject("unobserved").isNull("tasks"))}
 @Test fun wrongCityAuthoritativeAndHiddenRiskAreRefused(){refuses{parseMonitorGraph(graph(),"city-b")};val r=graph();r.getJSONObject("graph").put("authoritative",true);refuses{parseMonitorGraph(r,"city-a")};val h=graph();h.getJSONObject("graph").getJSONArray("visibleNodeIds").remove(0);refuses{parseMonitorGraph(h,"city-a")}}
 @Test fun duplicateAndOversizedNodesAreRefused(){val r=graph();val n=r.getJSONObject("graph").getJSONArray("nodes");n.put(n.getJSONObject(0));refuses{parseMonitorGraph(r,"city-a")};val big=graph();for(i in 1..520)big.getJSONObject("graph").getJSONArray("nodes").put(JSONObject().put("id","n$i"));refuses{parseMonitorGraph(big,"city-a")}}
 @Test fun decisionIdentityAndAdvisoryTruthAreRequired(){val r=JSONObject("""{"cityId":"city-a","window":{"schemaVersion":1,"authoritative":false,"decisions":[{"decisionId":"d1","ownerRequired":true,"appliedBy":null,"application":"RECORDED_ONLY","evidenceRefs":[],"decisionLatencyMs":null}]},"metrics":{"decisions":1}}""");assertTrue(parseMonitorDecisions(r,"city-a").getJSONObject("window").getJSONArray("decisions").getJSONObject(0).isNull("decisionLatencyMs"));refuses{parseMonitorDecisions(r,"city-b")};val receipt=r.getJSONObject("window").getJSONArray("decisions").getJSONObject(0);receipt.getJSONArray("evidenceRefs").put("bad");refuses{parseMonitorDecisions(r,"city-a")};receipt.put("evidenceRefs",org.json.JSONArray());receipt.put("appliedBy","monitor");refuses{parseMonitorDecisions(r,"city-a")}}
 @Test fun malformedPathsClustersAndDroppedNodesAreRefused(){val e=graph();e.getJSONObject("graph").getJSONArray("edges").put("bad");refuses{parseMonitorGraph(e,"city-a")};val ev=graph();ev.getJSONObject("graph").getJSONArray("events").put("bad");refuses{parseMonitorGraph(ev,"city-a")};val ptr=graph();ptr.getJSONObject("graph").getJSONArray("evidence").put("bad");refuses{parseMonitorGraph(ptr,"city-a")};val blank=graph();blank.getJSONObject("graph").getJSONArray("edges").put(JSONObject());refuses{parseMonitorGraph(blank,"city-a")};val c=graph();c.getJSONObject("graph").getJSONArray("clusters").getJSONObject(0).remove("id");refuses{parseMonitorGraph(c,"city-a")};val dropped=graph();dropped.getJSONObject("graph").getJSONArray("clusters").remove(0);refuses{parseMonitorGraph(dropped,"city-a")};val wrong=graph();wrong.getJSONObject("graph").getJSONArray("nodes").getJSONObject(1).put("clusterRef","wrong");refuses{parseMonitorGraph(wrong,"city-a")}}

}
