// EM-012 — Connector SDK + Claude Code / WorkBuddy extension paths.
export {
  CONNECTOR_SDK_VERSION,
  SDK_CONTRACT_VERSION,
  ADAPTER_FAMILIES,
  OPTIONAL_FAMILIES,
  ADAPTER_STATES,
  ADAPTER_FAULT_KINDS,
  ACCEPTANCE_PENDING,
  MINIMUM_CONNECTOR_METHODS,
  RESULT_STATES,
  TERMINAL_RESULT_STATES,
  CAPABILITY_SEMANTICS,
  AUTH_SEMANTICS,
  TEST_EXPECTATIONS,
  SDK_CODES,
  SdkError,
  defineConnector,
  runConformanceHarness,
  createSdkAdapter,
  createAdapterRegistry,
  extensionGuide,
  isIsoInstant,
} from './connector-sdk.mjs';
