import * as nativeIo from 'node:fs/promises';import {resolve,join} from 'node:path';import {createHash,randomUUID} from 'node:crypto';
import {requireThat as ok,finite,text,copy,freeze} from './validation.mjs';
export const sha256=bytes=>createHash('sha256').update(bytes).digest('hex');
// Explicit storage adapter; digest is integrity, authorize() is permission. No caller-controlled path.
export function createArtifactStore({root,maxBytes,maxItems,authorize,storageIo={}}){
 const {mkdir,writeFile,readFile,rename,unlink,stat,rmdir,readdir,appendFile}={...nativeIo,...storageIo};
 ok(text(root)&&finite(maxBytes)&&maxBytes>0&&Number.isInteger(maxItems)&&maxItems>0&&typeof authorize==='function','ARTIFACT_CONFIG');const base=resolve(root);let tail=Promise.resolve();
 const exclusive=fn=>{const p=tail.then(async()=>{await mkdir(base,{recursive:true});const lock=join(base,'.writer-lock');try{await mkdir(lock);}catch(e){throw Object.assign(new Error('ARTIFACT_WRITER_UNAVAILABLE'),{code:'ARTIFACT_WRITER_UNAVAILABLE',cause:e});}try{return await fn();}finally{await rmdir(lock);}});tail=p.catch(()=>{});return p;};
 const indexPath=join(base,'index.json');const index=async()=>{try{return JSON.parse(await readFile(indexPath,'utf8'));}catch(e){if(e.code==='ENOENT')return [];throw e;}};
 const putIndex=async entries=>{const temp=join(base,randomUUID()+'.index.tmp');try{await writeFile(temp,JSON.stringify(entries),{flag:'wx'});await rename(temp,indexPath);}finally{try{await unlink(temp);}catch(e){if(e.code!=='ENOENT')throw e;}}};
 const path=id=>{ok(typeof id==='string'&&/^[a-f0-9-]{36}$/.test(id),'OPAQUE_ARTIFACT_ID_REQUIRED');return join(base,id+'.blob');};
 const auditQuota=async entries=>{const files=await readdir(base),journals=[];for(const f of files.filter(f=>f.endsWith('.transfer.json')))journals.push(JSON.parse(await readFile(join(base,f),'utf8')));ok(files.every(f=>!f.endsWith('.blob')||entries.some(e=>f===e.id+'.blob')||journals.some(t=>['PUBLISHING','DELETE_PENDING','DELETE_FAILED'].includes(t.state)&&f===t.id+'.blob')),'ARTIFACT_ORPHAN');let bytes=0,items=entries.filter(e=>e.deletionState!=='DELETED').length+journals.filter(t=>!entries.some(e=>e.id===t.id)).length;for(const f of files){if(f.endsWith('.blob')||f.endsWith('.partial'))bytes+=(await stat(join(base,f))).size;}ok(bytes<=maxBytes&&items<=maxItems,'CACHE_QUOTA');return {bytes,items};};
 const alter=async(id,context,now,fn)=>exclusive(async()=>{path(id);const entries=await index(),entry=entries.find(e=>e.id===id);ok(entry&&await authorize({operation:'MANAGE',metadata:copy(entry),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED');fn(entry);await putIndex(entries);return copy(entry);});
 const transferPath=id=>{path(id);return join(base,id+'.transfer.json');};
 const loadTransfer=async id=>JSON.parse(await readFile(transferPath(id),'utf8'));
 const saveTransfer=async t=>{const temp=transferPath(t.id)+'.tmp';await writeFile(temp,JSON.stringify(t));await rename(temp,transferPath(t.id));};
 const transfer=async(id,context,now)=>{const t=await loadTransfer(id);ok(!t.cancelled,'TRANSFER_CANCELLED');ok(now<t.metadata.expiresAt&&await authorize({operation:'TRANSFER',metadata:copy(t.metadata),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED_OR_EXPIRED');return t;};
 const removeIfPresent=async p=>{try{await unlink(p);}catch(e){if(e.code!=='ENOENT')throw e;}};
 const cancel=async(id,context,now)=>{const t=await loadTransfer(id);ok(await authorize({operation:'DELETE',metadata:copy(t.metadata),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED');ok(!(await index()).some(e=>e.id===id),'TRANSFER_ALREADY_PUBLISHED');t.cancelled=true;t.state='DELETE_PENDING';await saveTransfer(t);try{await removeIfPresent(path(id)+'.partial');await removeIfPresent(path(id));await unlink(transferPath(id));return {id,state:'DELETED'};}catch(e){t.state='DELETE_FAILED';t.cleanupError=e.code;await saveTransfer(t);return {id,state:t.state,error:e.code};}};
 const cleanupPublished=async(t,ref)=>{try{await unlink(transferPath(t.id));}catch(e){if(e.code!=='ENOENT'){t.state='PUBLISHED_CLEANUP_FAILED';t.cleanupError=e.code;await saveTransfer(t);}}return freeze(ref);};
 return {
  publish(bytes,metadata,now){return exclusive(async()=>{ok(Buffer.isBuffer(bytes)&&bytes.length<=maxBytes,'ARTIFACT_LIMIT');ok(Object.keys(metadata).every(k=>['owner','dataScope','expiresAt','schema'].includes(k)),'ARTIFACT_METADATA_KEY');ok(text(metadata.owner)&&text(metadata.dataScope)&&finite(metadata.expiresAt)&&metadata.expiresAt>now,'ARTIFACT_METADATA');ok(await authorize({operation:'PUBLISH',metadata:copy(metadata),now}),'ARTIFACT_UNAUTHORIZED');const entries=await index(),quota=await auditQuota(entries);ok(quota.items<maxItems&&quota.bytes+bytes.length<=maxBytes,'CACHE_QUOTA');const ref={...copy(metadata),version:1,id:randomUUID(),digest:sha256(bytes),size:bytes.length};const target=path(ref.id),temp=target+'.partial';try{await writeFile(temp,bytes,{flag:'wx'});ok(await authorize({operation:'PUBLISH',metadata:copy(metadata),now}),'ARTIFACT_UNAUTHORIZED');await rename(temp,target);await putIndex([...entries,ref]);return freeze(ref);}catch(error){try{await removeIfPresent(temp);await removeIfPresent(target);}catch(cleanupError){await saveTransfer({id:ref.id,source:{digest:ref.digest,size:ref.size,version:ref.version},metadata:copy(metadata),cancelled:true,state:'DELETE_FAILED',cleanupError:cleanupError.code});}throw error;}});},
  async read(ref,context,now){path(ref.id);const entries=await index(),stored=entries.find(x=>x.id===ref.id);ok(stored&&stored.digest===ref.digest&&stored.size===ref.size&&stored.version===ref.version,'ARTIFACT_UNKNOWN');ok(!stored.revoked&&now<stored.expiresAt&&await authorize({operation:'READ',metadata:copy(stored),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED_OR_EXPIRED');const info=await stat(path(stored.id));ok(info.size===stored.size&&info.size<=maxBytes,'ARTIFACT_SIZE');const bytes=await readFile(path(stored.id));ok(sha256(bytes)===stored.digest,'ARTIFACT_DIGEST');return bytes;},
  pin(id,context,now){return alter(id,context,now,e=>{e.pinned=true;});},
  unpin(id,context,now){return alter(id,context,now,e=>{e.pinned=false;});},
  lease(id,context,until,now){ok(finite(until)&&until>now,'CACHE_LEASE');return alter(id,context,now,e=>{e.leaseUntil=until;});},
  evict(context,now){return exclusive(async()=>{const entries=await index(),deleted=[];for(const e of entries){if(e.pinned||e.leaseUntil>now||!await authorize({operation:'DELETE',metadata:copy(e),context:copy(context),now}))continue;try{await unlink(path(e.id));e.deletionState='DELETED';deleted.push(e.id);}catch(error){e.deletionState='DELETE_FAILED';e.deletionError=error.code;}}await putIndex(entries.filter(e=>e.deletionState!=='DELETED'));return {deleted,failed:entries.filter(e=>e.deletionState==='DELETE_FAILED').map(e=>({id:e.id,error:e.deletionError}))};});},
  revoke(id,context,now){return exclusive(async()=>{path(id);const entries=await index(),e=entries.find(e=>e.id===id);ok(e&&await authorize({operation:'DELETE',metadata:copy(e),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED');e.revoked=true;e.deletionState='DELETE_PENDING';await putIndex(entries);try{await unlink(path(id));e.deletionState='DELETED';}catch(error){e.deletionState='DELETE_FAILED';e.deletionError=error.code;}await putIndex(entries);return {id,state:e.deletionState,error:e.deletionError};});},
  status(id,context,now){return alter(id,context,now,()=>{});},
  beginTransfer(source,metadata,context,now){return exclusive(async()=>{ok(Object.keys(metadata).every(k=>['owner','dataScope','expiresAt','schema'].includes(k)),'ARTIFACT_METADATA_KEY');ok(Object.keys(source).every(k=>['digest','size','version'].includes(k))&&/^[a-f0-9]{64}$/.test(source.digest)&&Number.isSafeInteger(source.size)&&source.size>=0&&source.size<=maxBytes&&Number.isSafeInteger(source.version)&&source.version>0,'TRANSFER_BINDING');ok(text(metadata.owner)&&text(metadata.dataScope)&&text(metadata.schema)&&metadata.expiresAt>now&&await authorize({operation:'TRANSFER',metadata:copy(metadata),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED');const quota=await auditQuota(await index());ok(quota.items<maxItems&&quota.bytes+source.size<=maxBytes,'CACHE_QUOTA');const t={id:randomUUID(),source:copy(source),metadata:copy(metadata)};await writeFile(transferPath(t.id),JSON.stringify(t),{flag:'wx'});try{await writeFile(path(t.id)+'.partial',Buffer.alloc(0),{flag:'wx'});}catch(error){t.cancelled=true;t.state='DELETE_FAILED';t.cleanupError=error.code;await saveTransfer(t);throw error;}return copy(t);});},
  appendTransfer(id,bytes,offset,binding,context,now){return exclusive(async()=>{const t=await transfer(id,context,now);ok(binding.digest===t.source.digest&&binding.version===t.source.version,'TRANSFER_BINDING');const partial=path(id)+'.partial',info=await stat(partial);ok(Buffer.isBuffer(bytes)&&info.size===offset&&offset+bytes.length<=t.source.size,'TRANSFER_OFFSET');const quota=await auditQuota(await index());ok(quota.bytes+bytes.length<=maxBytes,'CACHE_QUOTA');await appendFile(partial,bytes);return {id,bytes:offset+bytes.length};});},
  finishTransfer(id,context,now){return exclusive(async()=>{path(id);const entries=await index(),existing=entries.find(e=>e.id===id);if(existing){ok(!existing.revoked&&now<existing.expiresAt&&await authorize({operation:'READ',metadata:copy(existing),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED_OR_EXPIRED');const bytes=await readFile(path(id));ok(bytes.length===existing.size&&sha256(bytes)===existing.digest,'TRANSFER_DIGEST');try{return await cleanupPublished(await loadTransfer(id),existing);}catch(e){if(e.code==='ENOENT')return freeze(existing);throw e;}}
   const t=await transfer(id,context,now),partial=path(id)+'.partial';let bytes,alreadyRenamed=false;try{bytes=await readFile(partial);}catch(e){if(e.code!=='ENOENT'||t.state!=='PUBLISHING')throw e;bytes=await readFile(path(id));alreadyRenamed=true;}
   ok(bytes.length===t.source.size&&sha256(bytes)===t.source.digest,'TRANSFER_DIGEST');ok(await authorize({operation:'PUBLISH',metadata:copy(t.metadata),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED');await auditQuota(entries);const ref={...t.metadata,...t.source,id};t.state='PUBLISHING';await saveTransfer(t);if(!alreadyRenamed)await rename(partial,path(id));await putIndex([...entries,ref]);return cleanupPublished(t,ref);});},
  cancelTransfer(id,context,now){return exclusive(()=>cancel(id,context,now));},
  cleanupExpiredTransfers(context,now){return exclusive(async()=>{const deleted=[],failed=[];for(const f of (await readdir(base)).filter(f=>f.endsWith('.transfer.json'))){const t=JSON.parse(await readFile(join(base,f),'utf8'));if(!(t.cancelled||now>=t.metadata.expiresAt)||!await authorize({operation:'DELETE',metadata:copy(t.metadata),context:copy(context),now}))continue;if((await index()).some(e=>e.id===t.id))continue;const result=await cancel(t.id,context,now);if(result.state==='DELETED')deleted.push(t.id);else failed.push(result);}return {deleted,failed};});},
  transferStatus(id,context,now){return exclusive(async()=>{const t=await loadTransfer(id);ok(await authorize({operation:'MANAGE',metadata:copy(t.metadata),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED');return {id,state:t.state??'PARTIAL',error:t.cleanupError};});},
  claimCheckpointRestore(ref,binding,fence,now){return exclusive(async()=>{const entry=(await index()).find(e=>e.id===ref.id);ok(entry&&!entry.revoked&&entry.digest===ref.digest&&now<entry.expiresAt&&await authorize({operation:'RESTORE',metadata:copy(entry),context:{caller:binding.owner,taskId:binding.taskId,attemptId:binding.attemptId,fence},now}),'ARTIFACT_UNAUTHORIZED_OR_EXPIRED');const claimPath=join(base,sha256(JSON.stringify([binding.taskId,binding.attemptId]))+'.restore-claim.json');try{await writeFile(claimPath,JSON.stringify({artifactId:ref.id,digest:ref.digest,taskId:binding.taskId,sourceAttemptId:binding.sourceAttemptId,targetAttemptId:binding.attemptId,fence}),{flag:'wx'});}catch(e){if(e.code==='EEXIST')ok(false,'CHECKPOINT_RESTORE_ALREADY_CLAIMED');throw e;}return true;});},
  invalidate(id,context,now){return exclusive(async()=>{const entries=await index(),stored=entries.find(x=>x.id===id);ok(stored&&await authorize({operation:'DELETE',metadata:copy(stored),context:copy(context),now}),'ARTIFACT_UNAUTHORIZED');await unlink(path(id));await putIndex(entries.filter(x=>x.id!==id));return true;});},
 };
}
